
function ImagePI(owner){this.owner=owner;this.bindsize=true;this.ratio=1;this.img_id="Properties_img_id_"+this.owner.name;this.img_width="Properties_img_width_"+this.owner.name;this.img_hspace="Properties_img_hspace_"+this.owner.name;this.img_align="Properties_img_align_"+this.owner.name;this.img_border="Properties_img_border_"+this.owner.name;this.img_height="Properties_img_height_"+this.owner.name;this.img_vspace="Properties_img_vspace_"+this.owner.name;this.img_src="Properties_img_src_"+this.owner.name;this.img_link="Properties_img_link_"+this.owner.name;this.img_link_browse=this.owner.name+"LinkBrowse";this.img_alt="Properties_img_alt_"+this.owner.name;this.img_src_browse="Properties_img_src_browse_"+this.owner.name;var idx=this.owner.toolbar.indexOfName('insert_image');if(idx<0){document.getElementById(this.img_src_browse).style.visibility="hidden";}};function ImagePI_apply(propName,propValue){var inspected=this.owner.inspectedNode;switch(propName){case"id":if(propValue!=""){this.owner.inspectedNode.setAttribute("id",propValue);}else{this.owner.inspectedNode.removeAttribute("id");}
break;case"src":if(propValue==document.getElementById(this.img_src).getAttribute("oldVal")){return;}
inspected.src=encodeURI(propValue);this.owner.logic_domSelect(inspected,2);break;case"height":case"width":if(propValue!=''&&propValue!='false'){inspected.setAttribute(propName,propValue);}else{inspected.removeAttribute(propName);}
if(this.bindsize){if(propName=='height'){if(propValue==''){inspected.removeAttribute('width');}else{inspected.width=inspected.height/this.ratio;}}else{if(propValue==''){inspected.removeAttribute('height');}else{inspected.height=inspected.width*this.ratio;}}}
inspected.style[propName]="";break;case"hspace":case"vspace":case"border":case"align":if(propValue!=''&&propValue!='false'){propValue=String(propValue);propValue=propValue.replace(/'/g,"\\'");inspected.setAttribute(propName,propValue);}else{inspected.removeAttribute(propName);}
break;case"link":var parA=utility.dom.getParentByTagName(inspected,"A");if(parA){if(propValue){parA.href=encodeURI(propValue);}else{var saveLink=parA;var saveImg=inspected;saveImg=saveLink.parentElement.insertBefore(saveImg,saveLink);saveImg.parentElement.removeChild(saveLink);this.owner.logic_domSelect(saveImg,2);}}else if(propValue){var uniq="newlink"+this.owner.getUniqueID();inspected.outerHTML='<a id="'+uniq+'" href="">'+inspected.outerHTML+'';var newLink=this.owner.edit.getElementById(uniq);newLink.removeAttribute("ID");newLink.removeAttribute("id");newLink.href=encodeURI(propValue);this.owner.logic_domSelect(newLink.firstChild,2);}
break;default:break;}
if(propName=='alt'){if(propValue!=''){inspected.setAttribute('title',propValue);inspected.setAttribute('alt',propValue);}else{inspected.removeAttribute('title');inspected.removeAttribute('alt');}}
try{fixFocusHack(0);}
catch(e){}};function ImagePI_inspect(propName,propValue){var inspected=this.owner.inspectedNode;this.ratio=inspected.height/inspected.width;util_safeSetFieldValue(this.img_id,inspected.getAttribute("id"));util_safeSetFieldValue(this.img_width,inspected.width);util_safeSetFieldValue(this.img_height,inspected.height);inspected.setAttribute('width',inspected.width);inspected.setAttribute('height',inspected.height);inspected.style.width='';inspected.style.height='';utility.dom.selectOption(document.getElementById(this.img_align),inspected.getAttribute("align")||"");util_safeSetFieldValue(this.img_border,inspected.getAttribute("border"));util_safeSetFieldValue(this.img_src,util_removeSiteNameFromHREF(this.owner,decodeURI(inspected.getAttribute("src").replace(/\?size=\d*$/,''))));var parA=utility.dom.getParentByTagName(inspected,"A");if(parA){var href='';if(is.ie){var m=parA.outerHTML.match(/\shref='?"?([^\s'"]*)/i);if(m){href=m[1];}}else{href=parA.getAttribute("href");}
var propValue=util_removeSiteNameFromHREF(this.owner,decodeURI(href));util_safeSetFieldValue(this.img_link,propValue);if(href.toLowerCase().indexOf("ktm/modules/filebrowser/display_image.html")>=0){document.getElementById(this.img_link).disabled=true;document.getElementById(this.img_link_browse).disabled=true;}else{document.getElementById(this.img_link).disabled=false;document.getElementById(this.img_link_browse).disabled=false;}}else{util_safeSetFieldValue(this.img_link,'');document.getElementById(this.img_link).disabled=false;document.getElementById(this.img_link_browse).disabled=false;}
util_safeSetFieldValue(this.img_hspace,/hspace=/i.test(inspected.outerHTML)?inspected.getAttribute("hspace"):"");util_safeSetFieldValue(this.img_vspace,/vspace=/i.test(inspected.outerHTML)?inspected.getAttribute("vspace"):"");util_safeSetFieldValue(this.img_alt,inspected.getAttribute("title"));};function ImagePI_bindImageSize(element,relpath){var obj=this;var inspected=this.owner.inspectedNode;if(!this.syh){this.syh=function(e){obj.syncHSize(e);};this.syw=function(e){obj.syncWSize(e);};}
var iw=document.getElementById(this.img_width);var ih=document.getElementById(this.img_height);if(this.bindsize){this.bindsize=false;element.setAttribute('src',relpath+'/ubound.gif');iw.onkeyup=function(){};ih.onkeyup=function(){};}else{this.bindsize=true;element.setAttribute('src',relpath+'/bound.gif');this.ratio=inspected.height/inspected.width;iw.onkeyup=function(e){var o=utility.dom.setEventVars(e);obj.syncHSize(o.e);};ih.onkeyup=function(e){var o=utility.dom.setEventVars(e);obj.syncWSize(o.e);};}};function ImagePI_syncWSize(e){if(e.keyCode==37||e.keyCode==39){return;}
var ih=document.getElementById(this.img_height);try{ih.value=parseInt(ih.value);var val=Math.floor(ih.value/this.ratio);if(isNaN(val)){val='';ih.value='';}
document.getElementById(this.img_width).value=val;}catch(e){ih.value='';}};function ImagePI_syncHSize(e){if(e.keyCode==37||e.keyCode==39){return;}
var iw=document.getElementById(this.img_width);try{iw.value=parseInt(iw.value);var val=Math.floor(iw.value*this.ratio);if(isNaN(val)){val='';iw.value='';}
document.getElementById(this.img_height).value=val;}catch(e){iw.value='';}};ImagePI.prototype.apply=ImagePI_apply;ImagePI.prototype.inspect=ImagePI_inspect;ImagePI.prototype.bindImageSize=ImagePI_bindImageSize;ImagePI.prototype.syncHSize=ImagePI_syncHSize;ImagePI.prototype.syncWSize=ImagePI_syncWSize;window.KtmlPIObjects["img"]=ImagePI;