
ktml.prototype.init_fillCssClasses2=function(){var cssuri=this.toolbar.styler;if(!cssuri){return;}
cssuri=KTStorage.get(cssuri);if(cssuri.options.length==1){var blockformats_styles=[];var dict=[];var stylesArr=[];var rules=is.ie?this.attachedStyleSheet.styleSheet.rules:this.attachedStyleSheet.sheet.cssRules;for(var i=0;i<rules.length;i++){var st=rules[i].selectorText;if(!st){continue;}
var cssText=rules[i].style.cssText;st=st.split(/[,]/);for(var j=0;j<st.length;j++){var os=String_trim(st[j]);if(os==''||os.match(/\s+/)){continue;}
var spl=os.split(".");if(spl.length==2){var item={"tagName":"","className":"","displayName":"","cssText":""};if(spl[0]==""){var cssStyleItemName=spl[1];item.displayName=""+spl[1];}else{item.tagName=spl[0].toLowerCase();var cssStyleItemName=item.tagName+"."+spl[1].replace(/:.*$/,'');item.displayName=cssStyleItemName;}
item.className=spl[1];item.cssText=cssText;if(typeof dict[cssStyleItemName.toLowerCase()]=="undefined"){stylesArr.push(item);dict[cssStyleItemName.toLowerCase()]=cssStyleItemName.toLowerCase();}else{var existingStyleItem=findObjectInArrayByProperty(stylesArr,"displayName","."+cssStyleItemName.toLowerCase());if(existingStyleItem){existingStyleItem.cssText+=";"+item.cssText;}}}else if(spl.length==1){os=os.toLowerCase();blockformats_styles.push({tag:os,style:cssText});}}}
if(blockformats_styles.length){var stl=document.createStyleSheet("");var selector,cssText,theTextNode;for(var i=0;i<blockformats_styles.length;i++){selector='.optcontainer '+blockformats_styles[i].tag;cssText=blockformats_styles[i].style;if(is.ie){try{stl.addRule(selector,cssText);}catch(e){}}else{theTextNode=document.createTextNode(selector+" { "+cssText+" }");stl.appendChild(theTextNode);}}}
cssuri.styleArray=stylesArr.sort(keySort);cssuri.load=p_lateAdd;cssuri.removeAll=cssdropdown_removeAll;cssuri.load();}}
ktml.prototype.init_fillCssClasses=function(){var _this=this;if(this.edit.readyState!="complete"){setTimeout(function(){_this.init_fillCssClasses();},400);return;}else{this.attachedStyleSheet=null;var styles=this.edit.getElementsByTagName("link");for(var i=0;i<styles.length;i++){if(styles[i].getAttribute('id')=='styler'){this.attachedStyleSheet=styles[i];break;}}
if(!this.attachedStyleSheet){return;}
if(!this.toolbar.lateLoaded){this.toolbar.deferredfunctors.push(Function_bind(ktml.prototype.init_fillCssClasses2,_this));}else{this.init_fillCssClasses2();}}};function cssdropdown_removeAll(){this.removeAll();};function findObjectInArrayByProperty(arr,propertyName,propertyValue){for(var i=0;i<arr.length;i++){var oneItem=arr[i];if(oneItem[propertyName]==propertyValue){return oneItem;}}
return null;};function keySort(a,b){var v1=a.displayName;var v2=b.displayName;return(v1==v2?0:(v1<v2?-1:1));};function p_lateAdd(){if(window.pla){window.clearTimeout(window.pla);}
var ccc=this;lateAdd(ccc,this.styleArray);};function lateAdd(obj,arr,force){if(typeof force=="undefined"){force=false;}
if(!force&&obj.optContainerTable.rows.length>1){return;}
var cssText='';for(var i=0;i<arr.length;i++){var cssStyleItem=arr[i];cssText=cssStyleItem.cssText;var v='<div style="'+cssText.replace(/"/gi,'')+';position:static ! important; width:140px ! important; max-height:30px; overflow:hidden; margin:0px ! important; padding:2px ! important;">'+cssStyleItem.displayName+'</div>';obj.add(cssStyleItem.displayName,v);}};ktml.prototype.util_safeSetClassAttribute=function(el,className){var styleTagName="";if(className!=""){var spl=className.split(/\./);if(spl.length==2){styleTagName=spl[0].toLowerCase();className=spl[1];}else{className=spl[0];}}
var ret=false;var pel=el.parentNode;if(el.nodeType==1){if(is.mozilla&&el.nodeName=="BR"){if(first_child(pel)==el&&last_child(pel)==el){ret=this.util_safeSetClassAttribute(pel,className);}else{var span=this.edit.createElement("SPAN");this.util_safeSetClassAttribute(span,className);span.innerHTML="<br>";el.parentNode.replaceChild(span,el);ret=span;}}else if(el.nodeName=="BODY"){var fc=is.mozilla?first_child(el):el.firstChild;var lc=is.mozilla?last_child(el):el.lastChild;if(is.mozilla&&fc.nodeName=="BR"&&fc==lc){var span=this.edit.createElement("SPAN");this.util_safeSetClassAttribute(span,className);span.innerHTML="<br>";el.parentNode.replaceChild(span,el);ret=span;}else{for(var i=0;i<el.childNodes.length;i++){this.util_safeSetClassAttribute(el.childNodes[i],className);}}}else{if(styleTagName&&styleTagName!=el.nodeName.toLowerCase()){return;}
if(className==""){el.className="";el.attributes.removeNamedItem("class");}else{el.className=className;}}}else if(el.nodeType==3){if(pel){if(is.mozilla){var fc=first_child(pel);var lc=last_child(pel);if(lc&&lc.nodeName=="BR"){lc=node_before(lc);}
if(fc==el&&lc==el){ret=this.util_safeSetClassAttribute(pel,className);}else{var span=this.edit.createElement("SPAN");this.util_safeSetClassAttribute(span,className);span.textContent=el.textContent;el.parentNode.replaceChild(span,el);this.util_safeSetClassAttribute(span,className);ret=span;}}else{var span=this.edit.createElement("SPAN");this.util_safeSetClassAttribute(span,className);span.innerText=el.nodeValue;el.parentNode.replaceChild(span,el);ret=span;}}else{el.attributes.removeNamedItem("class");var span=this.edit.createElement("SPAN");span.appendChild(el);this.util_safeSetClassAttribute(span,className);ret=span;}}
return ret;};ktml.prototype.ui_updateStyle=function(){var styleSelect=KTStorage.get(this.toolbar.styler);if(!styleSelect){return;}
if(typeof styleSelect['styleArray']=='undefined'){return;}
var t1=new Date();var selectedIndex=0;var curClassName='';var curTagName='';var curClass='';var done=false;if(this.displayMode=='RICH'){for(var h=0;!done&&h<this.selectableNodes.length;h++){curClassName=this.selectableNodes[h].className.toLowerCase();if(curClassName!=""){curTagName=this.selectableNodes[h].tagName.toLowerCase();for(var hh=0;hh<styleSelect.options.length;hh++){curClass=findObjectInArrayByProperty(styleSelect.styleArray,"displayName",styleSelect.options[hh].value);if(curClass&&(curClass.tagName==curTagName||curClass.tagName=="")&&curClass.className.toLowerCase()==curClassName){selectedIndex=hh;done=true;break;}}}}}
styleSelect.selectedIndex=selectedIndex;styleSelect.pickValue(selectedIndex);};function css_callback_update(){this.ui_updateStyle();};function css_runonce(){};function css_runeach(k){k.init_fillCssClasses();k.hooks['onupdatebuttonstate'].push(css_callback_update);var cmd="this.ktml.cw.focus();if(this.ktml.undo){this.ktml.undo.addEdit();};this.ktml.logic_InsertStyle(this.value);if(this.ktml.undo){this.ktml.undo.addEdit();};this.ktml.cw.focus();this.ktml.ui_setButtonState();";var idx=k.toolbar.indexOfName('style_list');if(idx>=0){k.toolbar.buttonobjects[idx].command=cmd;}else{k.toolbar.deferredcommands['style_list']=cmd;}};