'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShowOrder

    '''<summary>
    '''ConfirmOrderTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmOrderTable As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''EmailHyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailHyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''CustomerNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CompanyLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CustomerEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MailingAddress1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MailingAddress1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MailingCityStateCountryLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MailingCityStateCountryLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MailingPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MailingPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MailingFaxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MailingFaxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShippingAddress1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingAddress1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShippingAddress2Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingAddress2Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShippingCityStateCountryLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingCityStateCountryLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PaymentMethodLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentMethodLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShipMethodLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipMethodLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImagesRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagesRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''BooksRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BooksRepeater As Global.System.Web.UI.WebControls.Repeater
End Class
