'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShowImage
    
    '''<summary>
    '''NameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Signed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Signed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ContactUsHyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactUsHyperLink As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''SignedAvailableHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignedAvailableHF As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RefidLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefidLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OtherVariationsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherVariationsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ViewBWButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewBWButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ViewBWCroppedButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewBWCroppedButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ViewColorButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewColorButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ViewColorCroppedButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewColorCroppedButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''FavoritesMultiView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FavoritesMultiView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''AddFavoriteView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddFavoriteView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''AddToFavoritesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddToFavoritesButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RemoveFavoriteView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RemoveFavoriteView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''RemoveFromFavoritesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RemoveFromFavoritesButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''AddToCartButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddToCartButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BackButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DescLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RefidHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefidHiddenField As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''CookieStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CookieStatusLabel As Global.System.Web.UI.WebControls.Label
End Class
