'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TheGallery

    '''<summary>
    '''PhotographerDropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotographerDropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PhotographerDropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotographerDropDownList2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PhotoTypeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotoTypeDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RaceTypeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RaceTypeDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''MakeOfCarDropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MakeOfCarDropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''MakeOfCarDropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MakeOfCarDropDownList2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DriversDropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DriversDropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DriversDropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DriversDropDownList2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''YearDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YearDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PhotographersSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotographersSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PhotoTypeSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotoTypeSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RaceTypeSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RaceTypeSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''MakeOfCarSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MakeOfCarSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DriverSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DriverSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
