
function TableCellPI(owner){this.owner=owner;this.td_id="Properties_td_id_"+this.owner.name;this.td_width="Properties_td_width_"+this.owner.name;this.td_height="Properties_td_height_"+this.owner.name;this.td_align="Properties_td_align_"+this.owner.name;this.td_valign="Properties_td_valign_"+this.owner.name;this.td_bgimage="Properties_td_bgimage_"+this.owner.name;this.td_bgcolor="Properties_td_bgcolor_"+this.owner.name;this.td_brdcolor="Properties_td_brdcolor_"+this.owner.name;this.td_nowrap="Properties_td_nowrap_"+this.owner.name;this.td_header="Properties_td_header_"+this.owner.name;this.td_brdmonitor="Properties_td_brdColorMonitor_"+this.owner.name;this.td_bgmonitor="Properties_td_bgColorMonitor_"+this.owner.name;this.td_bgimage_browse="Properties_td_bgimage_browse_"+this.owner.name;var idx=this.owner.toolbar.indexOfName('insert_image');if(idx<0){document.getElementById(this.td_bgimage_browse).style.visibility="hidden";}};function TableCellPI_apply(propName,propValue){if(propValue!=''&&propValue!='false'){propValue=String(propValue);propValue=propValue.replace(/'/g,"\\'");switch(propName){case"header":var told=this.owner.inspectedNode;var tnew=this.owner.edit.createElement(propValue);for(var i=0;i<told.attributes.length;i++){var attr=told.attributes[i];fn=attr.nodeName;fv=attr.value;if(attr&&attr.specified){if(fn=="style"){tnew.style.cssText=told.style.cssText;}else{try{tnew.setAttribute(fn,fv);}catch(e){alert("Unable to copy attribute:\r\n"+utility.debug.dumpone(attr));}}}}
tnew.innerHTML=told.innerHTML;told.parentNode.replaceChild(tnew,told);this.owner.logic_domSelect(tnew);window.focus();document.getElementById(this.td_header).focus();break;case"noWrap":this.owner.inspectedNode.style.whiteSpace="nowrap";window.focus();document.getElementById(this.td_nowrap).focus();break;case"bgimage":document.getElementById(this.td_bgimage).value=decodeURI(util_removeSiteNameFromHREF(this.owner,propValue.replace(/\?size=\d*$/,'')));this.owner.inspectedNode.style.backgroundImage='url('+encodeURI(propValue)+')';break;case"bgColor":this.owner.inspectedNode.style.backgroundColor=propValue;try{document.getElementById(this.td_bgmonitor).style.backgroundColor=propValue;}catch(e){};break;case"borderColor":this.owner.inspectedNode.style.borderStyle="solid";this.owner.inspectedNode.style.borderWidth="1px";this.owner.inspectedNode.style.borderColor=propValue;try{document.getElementById(this.td_brdmonitor).style.backgroundColor=propValue;}catch(e){};break;default:this.owner.inspectedNode.setAttribute(propName,propValue);}}else{switch(propName){case"noWrap":while(this.owner.inspectedNode.getAttribute('nowrap')){this.owner.inspectedNode.removeAttribute('nowrap');this.owner.inspectedNode.removeAttribute('noWrap');this.owner.inspectedNode.removeAttribute('NOWRAP');}
this.owner.inspectedNode.style.whiteSpace="";window.focus();document.getElementById(this.td_nowrap).focus();break;case"bgimage":this.owner.inspectedNode.style.backgroundImage='';break;case"bgColor":this.owner.inspectedNode.style.backgroundColor="";try{document.getElementById(this.td_bgmonitor).style.backgroundColor="transparent";}catch(e){};break;case"borderColor":this.owner.inspectedNode.style.borderColor="";this.owner.inspectedNode.style.borderWidth="";this.owner.inspectedNode.style.borderStyle="";try{document.getElementById(this.td_brdmonitor).style.backgroundColor="transparent";}catch(e){};break;default:this.owner.inspectedNode.removeAttribute(propName);}}
try{fixFocusHack(0);}
catch(e){}};function TableCellPI_inspect(propName,propValue){util_safeSetFieldValue(this.td_id,this.owner.inspectedNode.getAttribute("id"));PropertiesUI_prop_getDimensions(this.owner.inspectedNode);util_safeSetFieldValue(this.td_width,this.owner.inspectedNode.getAttribute("width"));util_safeSetFieldValue(this.td_height,this.owner.inspectedNode.getAttribute("height"));utility.dom.selectOption(document.getElementById(this.td_align),this.owner.inspectedNode.getAttribute("align")||"");utility.dom.selectOption(document.getElementById(this.td_valign),this.owner.inspectedNode.getAttribute("vAlign")||"");var bgUrl=this.owner.inspectedNode.style.backgroundImage;if(bgUrl){var m=bgUrl.match(/url\(([^\)]*)\)/i);if(m){bgUrl=m[1];}
bgUrl=decodeURI(util_removeSiteNameFromHREF(this.owner,bgUrl.replace(/\?size=\d*$/,'')));}
util_safeSetFieldValue(this.td_bgimage,bgUrl);var _bgColor=this.owner.inspectedNode.style.backgroundColor;_bgColor=makeHexaColorCode(_bgColor);util_safeSetFieldValue(this.td_bgcolor,_bgColor);try{document.getElementById(this.td_bgmonitor).style.backgroundColor=_bgColor;}catch(e){};var _brdColor=this.owner.inspectedNode.style.borderColor;_brdColor=makeHexaColorCode(_brdColor);util_safeSetFieldValue(this.td_brdcolor,_brdColor);try{document.getElementById(this.td_brdmonitor).style.backgroundColor=_brdColor;}catch(e){};var cellHasNowrapSet=(this.owner.inspectedNode.style.whiteSpace=="nowrap")?true:false;document.getElementById(this.td_nowrap).checked=cellHasNowrapSet;document.getElementById(this.td_header).checked=(this.owner.inspectedNode.tagName=='TH');};function makeHexaColorCode(inputValue){var colorInHexa=/\#[abcdef0123456789]{6}/i;if(colorInHexa.test(inputValue)){return inputValue.toUpperCase();}
var colorInRGB=/rgb\((\d{1,3})\,\s{0,1}(\d{1,3})\,\s{0,1}(\d{1,3})\)/i;if(colorInRGB.test(inputValue)){var _digits="0123456789ABCDEF";function decimal2hexa(val){var result=_digits.substr(val&15,1);while(val>15){val>>=4;result=_digits.substr(val&15,1)+result;}
return result;}
var values=inputValue.match(colorInRGB);var result='#';for(var i=1;i<=3;i++){var _current=values[i];var _translated=decimal2hexa(_current);_translated=(_translated.length==1)?'0'+_translated:_translated;result+=_translated;}
return result.toUpperCase();}
return'';};TableCellPI.prototype.apply=TableCellPI_apply;TableCellPI.prototype.inspect=TableCellPI_inspect;window.KtmlPIObjects["td"]=TableCellPI;