'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Klemcoll

    Partial Public Class Images
        Inherits XPLiteObject
        Dim fImagesID As Integer
        <Key(True)>
        Public Property ImagesID() As Integer
            Get
                Return fImagesID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("ImagesID", fImagesID, value)
            End Set
        End Property
        Dim fRefid As String
        <Size(255)>
        Public Property Refid() As String
            Get
                Return fRefid
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Refid", fRefid, value)
            End Set
        End Property
        Dim fListItems As Integer
        Public Property ListItems() As Integer
            Get
                Return fListItems
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("ListItems", fListItems, value)
            End Set
        End Property
        Dim fCropVersion As Integer
        Public Property CropVersion() As Integer
            Get
                Return fCropVersion
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("CropVersion", fCropVersion, value)
            End Set
        End Property
        Dim fSignedAvailable As Integer
        Public Property SignedAvailable() As Integer
            Get
                Return fSignedAvailable
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("SignedAvailable", fSignedAvailable, value)
            End Set
        End Property
        Dim fSequence As String
        <Size(255)>
        Public Property Sequence() As String
            Get
                Return fSequence
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Sequence", fSequence, value)
            End Set
        End Property
        Dim fName As String
        <Size(255)>
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fDescription As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fPhotographerFirstName As String
        <Size(255)>
        Public Property PhotographerFirstName() As String
            Get
                Return fPhotographerFirstName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PhotographerFirstName", fPhotographerFirstName, value)
            End Set
        End Property
        Dim fPhotographerLastName As String
        <Size(255)>
        Public Property PhotographerLastName() As String
            Get
                Return fPhotographerLastName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PhotographerLastName", fPhotographerLastName, value)
            End Set
        End Property
        Dim fPhotoType As String
        <Size(255)>
        Public Property PhotoType() As String
            Get
                Return fPhotoType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PhotoType", fPhotoType, value)
            End Set
        End Property
        Dim fRaceType As String
        <Size(255)>
        Public Property RaceType() As String
            Get
                Return fRaceType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RaceType", fRaceType, value)
            End Set
        End Property
        Dim fMakeOfCar As String
        <Size(255)>
        Public Property MakeOfCar() As String
            Get
                Return fMakeOfCar
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MakeOfCar", fMakeOfCar, value)
            End Set
        End Property
        Dim fPhotoYear As String
        <Size(255)>
        Public Property PhotoYear() As String
            Get
                Return fPhotoYear
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PhotoYear", fPhotoYear, value)
            End Set
        End Property
        Dim fDriverFirstName As String
        <Size(255)>
        Public Property DriverFirstName() As String
            Get
                Return fDriverFirstName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DriverFirstName", fDriverFirstName, value)
            End Set
        End Property
        Dim fDriverLastName As String
        <Size(255)>
        Public Property DriverLastName() As String
            Get
                Return fDriverLastName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DriverLastName", fDriverLastName, value)
            End Set
        End Property
    End Class

End Namespace
