
function Embed_FlashPI(owner){this.owner=owner;this.props='props_simple,props_advanced,props_simple_btn,props_advanced_btn,id,width,height,filename,loop,play,hspace,vspace,quality,scale,align,bgcolor,alternate'.split(",");for(var i=0;i<this.props.length;i++){this["ctrl_"+this.props[i]]="Properties_embed_flash_"+this.props[i]+"_"+this.owner.name;}
this.reset="Properties_embed_flash_resetsize_"+this.owner.name;this.btn1="Properties_embed_flash_playstop1_"+this.owner.name;this.btn2="Properties_embed_flash_playstop2_"+this.owner.name;this.embed_flash_alternate_browse="Properties_embed_flash_alternate_browse_"+this.owner.name;this.embed_flash_src_browse="Properties_embed_flash_src_browse_"+this.owner.name;this.embed_flash_bgMonitor="Properties_embed_flash_bgcolorMonitor_"+this.owner.name;var idx=this.owner.toolbar.indexOfName('insert_image');if(idx<0){document.getElementById(this.embed_flash_src_browse).style.visibility="hidden";document.getElementById(this.embed_flash_alternate_browse).style.visibility="hidden";}
if(is.mozilla){document.getElementById(this.reset).style.visibility="hidden";}};function Embed_FlashPI_apply(propName,propValue){var inspected=this.owner.inspectedNode;if(/img/i.test(inspected.tagName)&&inspected.getAttribute("orig")){inspected=new WMedia_Translator(this.owner);}
propName=propName.toLowerCase();switch(propName){case"id":if(propValue!=""){inspected.setAttribute("id",propValue);}else{inspected.removeAttribute("id");}
break;case"filename":inspected.setAttribute(propName,propValue?encodeURI(propValue):"");break;case"loop":case"play":inspected.setAttribute(propName,propValue?"true":"false");break;case"bgcolor":var _color=propValue?propValue:"";inspected.setAttribute(propName,_color);try{document.getElementById(this.embed_flash_bgMonitor).style.backgroundColor=_color;}catch(e){};break;case"scale":case"quality":inspected.setAttribute(propName,propValue?propValue:"");break;case"align":if(propValue!=""){inspected.translated.align=propValue;inspected.setAttribute(propName,propValue);}else{inspected.translated.removeAttribute("align");inspected.removeAttribute(propName);}
break;case"width":inspected.translated.style.width="";if(propValue!=""){inspected.translated.width=propValue;inspected.setAttribute(propName,propValue);}else{inspected.translated.removeAttribute("width");inspected.removeAttribute(propName);}
break;case"height":inspected.translated.style.height="";if(propValue!=""){inspected.translated.height=propValue;inspected.setAttribute(propName,propValue);}else{inspected.translated.removeAttribute("height");inspected.removeAttribute(propName);}
break;case"hspace":case"vspace":if(propValue!=''){inspected.translated.setAttribute(propName,propValue);inspected.setAttribute(propName,propValue);}else{inspected.translated.removeAttribute(propName);inspected.removeAttribute(propName);}
break;case"start":orig_autostart=inspected.getAttribute("play");inspected.setAttribute("play","true");document.getElementById(this.btn1).value=translate("Stop");document.getElementById(this.btn2).value=translate("Stop");if(is.ie){this.owner.edit.selection.empty();inspected.play(propValue);}else{var play_window=utility.window.openWindow("MoviePlayerWindow"+parseInt(Math.random()*1000000000),KtmlRoot+"modules/introspection/tags/movie_player.html",400,280);window.play_window_arguments={ktml_counter:this.owner.counter,movie_html:inspected.outerHTML};this.owner.MediaPlayer=inspected;}
return;case"stop":inspected.setAttribute("play",orig_autostart+"");inspected.stop(propValue);document.getElementById(this.btn1).value=translate("Play");document.getElementById(this.btn2).value=translate("Play");return;case"alternate":if(propValue!=''){inspected.translated.setAttribute('title',propValue);inspected.setAttribute(propName,encodeURI(propValue));}else{inspected.translated.removeAttribute('title');inspected.removeAttribute(propName);}
util_safeSetFieldValue(this.ctrl_alternate,decodeURI(util_removeSiteNameFromHREF(this.owner,propValue)));break;default:alert("Setter for "+propName+" not implemented yet!\r\n[in Embed_FlashPI_apply]");}
try{fixFocusHack(0);}
catch(e){}};function Embed_FlashPI_inspect(propName,propValue){var inspected=this.owner.inspectedNode;if(/img/i.test(inspected.tagName)&&inspected.getAttribute("orig")){inspected=new WMedia_Translator(this.owner);}
util_safeSetFieldValue(this.ctrl_id,inspected.getAttribute("id"));var propValue=inspected.translated.getAttribute("width");util_safeSetFieldValue(this.ctrl_width,propValue);inspected.setAttribute("width",propValue);var propValue=inspected.translated.getAttribute("height");util_safeSetFieldValue(this.ctrl_height,propValue);inspected.setAttribute("height",propValue);util_safeSetFieldValue(this.ctrl_filename,decodeURI(util_removeSiteNameFromHREF(this.owner,inspected.getAttribute("filename"))));util_safeSetFieldValue(this.ctrl_alternate,decodeURI(util_removeSiteNameFromHREF(this.owner,inspected.getAttribute("alternate"))));var propValue=inspected.getAttribute("loop");document.getElementById(this.ctrl_loop).checked=(propValue=="true"?true:false);var propValue=inspected.getAttribute("play")+"";document.getElementById(this.ctrl_play).checked=(propValue=="true"?true:false);util_safeSetFieldValue(this.ctrl_hspace,inspected.getAttribute("hspace"));util_safeSetFieldValue(this.ctrl_vspace,inspected.getAttribute("vSpace"));var propValue=inspected.getAttribute("quality");utility.dom.selectOption(document.getElementById(this.ctrl_quality),propValue?propValue.toLowerCase():'');var propValue=inspected.getAttribute("scale");utility.dom.selectOption(document.getElementById(this.ctrl_scale),propValue?propValue.toLowerCase():'');var propValue=inspected.getAttribute("align");utility.dom.selectOption(document.getElementById(this.ctrl_align),propValue?propValue.toLowerCase():'');var propValue=inspected.getAttribute("bgColor");util_safeSetFieldValue(this.ctrl_bgcolor,propValue);try{document.getElementById(this.embed_flash_bgMonitor).style.backgroundColor=propValue;}catch(e){}};function Embed_FlashPI_resetSize(w,h){if(typeof(w)=="undefined"){top.resumer_translator=this;this.apply("start",true);}else{this.apply("width",w);this.apply("height",h);this.apply("stop");try{document.getElementById(this.reset).focus();}catch(err){}}};Embed_FlashPI.prototype.resetSize=Embed_FlashPI_resetSize;Embed_FlashPI.prototype.apply=Embed_FlashPI_apply;Embed_FlashPI.prototype.inspect=Embed_FlashPI_inspect;window.KtmlPIObjects["embed_flash"]=Embed_FlashPI;tmp_flash_string_holder=null;tmp_flash_owner_ktml=null;