
function TableRowPI(owner){this.owner=owner;this.tr_id="Properties_tr_id_"+this.owner.name;this.tr_align="Properties_tr_align_"+this.owner.name;this.tr_valign="Properties_tr_valign_"+this.owner.name;this.tr_bgimage="Properties_tr_bgimage_"+this.owner.name;this.tr_bgcolor="Properties_tr_bgcolor_"+this.owner.name;this.tr_brdcolor="Properties_tr_brdcolor_"+this.owner.name;this.tr_nowrap="Properties_tr_nowrap_"+this.owner.name;this.tr_header="Properties_tr_header_"+this.owner.name;this.tr_bgimage_browse="Properties_tr_bgimage_browse_"+this.owner.name;this.tr_bgmonitor="Properties_tr_bgColorMonitor_"+this.owner.name;this.tr_brdmonitor="Properties_tr_brdColorMonitor_"+this.owner.name;var idx=this.owner.toolbar.indexOfName('insert_image');if(idx<0){document.getElementById(this.tr_bgimage_browse).style.visibility="hidden";}};function TableRowPI_apply(propName,propValue){if(propValue!=''&&propValue!='false'){propValue=String(propValue);propValue=propValue.replace(/'/g,"\\'");switch(propName){case"nowrap":var cells=this.owner.inspectedNode.childNodes;for(var i=0;i<cells.length;i++){if(cells[i].nodeName&&(cells[i].nodeName.toLowerCase()=='td'||cells[i].nodeName.toLowerCase()=='th')){while(cells[i].getAttribute('nowrap')){cells[i].removeAttribute('nowrap');cells[i].removeAttribute('noWrap');cells[i].removeAttribute('NOWRAP');}
cells[i].style.whiteSpace="nowrap";}}
window.focus();document.getElementById(this.tr_nowrap).focus();break;case"header":for(var j=this.owner.inspectedNode.cells.length-1;j>=0;j--){var told=this.owner.inspectedNode.cells[j];var tnew=this.owner.edit.createElement(propValue);for(var i=0;i<told.attributes.length;i++){var attr=told.attributes[i];fn=attr.nodeName;fv=attr.value;if(attr&&attr.specified){if(fn=="style"){tnew.style.cssText=told.style.cssText;}else{try{tnew.setAttribute(fn,fv);}catch(e){}}}}
tnew.innerHTML=told.innerHTML;this.owner.inspectedNode.replaceChild(tnew,told);}
this.owner.logic_domSelect(0);document.getElementById(this.tr_header).focus();break;case"bgimage":document.getElementById(this.tr_bgimage).value=decodeURI(util_removeSiteNameFromHREF(this.owner,propValue.replace(/\?size=\d*$/,'')));this.owner.inspectedNode.style.backgroundImage='url('+encodeURI(propValue)+')';break;case"bgColor":this.owner.inspectedNode.style.backgroundColor=propValue;try{document.getElementById(this.tr_bgmonitor).style.backgroundColor=propValue;}catch(e){};break;case"borderColor":var children=this.owner.inspectedNode.childNodes;for(var i=0;i<children.length;i++){if(children[i].nodeName&&(children[i].nodeName.toLowerCase()=="td"||children[i].nodeName.toLowerCase()=="th")){children[i].style.borderStyle='solid';children[i].style.borderWidth='1px';children[i].style.borderColor=propValue;try{document.getElementById(this.tr_brdmonitor).style.backgroundColor=propValue;}catch(e){};}}
break;default:this.owner.inspectedNode.setAttribute(propName,propValue);}}else{switch(propName){case"nowrap":var cells=this.owner.inspectedNode.childNodes;for(var i=0;i<cells.length;i++){if(cells[i].nodeName&&(cells[i].nodeName.toLowerCase()=='td'||cells[i].nodeName.toLowerCase()=='th')){while((cells[i].getAttribute('nowrap'))){cells[i].removeAttribute('nowrap');cells[i].removeAttribute('noWrap');cells[i].removeAttribute('NOWRAP');}
cells[i].style.whiteSpace="";}}
window.focus();document.getElementById(this.tr_nowrap).focus();break;case"bgColor":this.owner.inspectedNode.style.backgroundColor="transparent";document.getElementById(this.tr_bgmonitor).style.backgroundColor="transparent";while(this.owner.inspectedNode.getAttribute("bgColor")){this.owner.inspectedNode.removeAttribute("bgColor");this.owner.inspectedNode.removeAttribute("bgcolor");this.owner.inspectedNode.removeAttribute("BGCOLOR");}
break;case"bgimage":this.owner.inspectedNode.style.backgroundImage='';break;case"borderColor":var children=this.owner.inspectedNode.childNodes;for(var i=0;i<children.length;i++){if(children[i].nodeName&&(children[i].nodeName.toLowerCase()=="td"||children[i].nodeName.toLowerCase()=="th")){children[i].style.borderColor="";children[i].style.borderwidth="";children[i].style.borderStyle="inset";document.getElementById(this.tr_brdmonitor).style.backgroundColor="transparent";}}
break;default:this.owner.inspectedNode.removeAttribute(propName);}}
try{fixFocusHack(0);}
catch(e){}};function TableRowPI_inspect(){var inspected=this.owner.inspectedNode;util_safeSetFieldValue(this.tr_id,this.owner.inspectedNode.id);utility.dom.selectOption(document.getElementById(this.tr_align),inspected.getAttribute("align")||"");utility.dom.selectOption(document.getElementById(this.tr_valign),inspected.getAttribute("vAlign")||"");var bgUrl=this.owner.inspectedNode.style.backgroundImage;if(bgUrl){var m=bgUrl.match(/url\(([^\)]*)\)/i);if(m){bgUrl=m[1]};bgUrl=decodeURI(util_removeSiteNameFromHREF(this.owner,bgUrl.replace(/\?size=\d*$/,'')));}
util_safeSetFieldValue(this.tr_bgimage,bgUrl);var _bgcolor=inspected.style.backgroundColor;_bgcolor=makeHexaColorCode(_bgcolor);util_safeSetFieldValue(this.tr_bgcolor,_bgcolor);try{document.getElementById(this.tr_bgmonitor).style.backgroundColor=_bgcolor;}catch(e){}
var trHasNowrapSet=false;for(var i=0;i<inspected.childNodes.length;i++){if(inspected.childNodes[i].nodeType==1&&(inspected.childNodes[i].nodeName.toLowerCase()=="td"||inspected.childNodes[i].nodeName.toLowerCase()=="th")){if(inspected.childNodes[i].style.whiteSpace=="nowrap"||inspected.childNodes[i].getAttribute('nowrap')){trHasNowrapSet=true;}}}
document.getElementById(this.tr_nowrap).checked=trHasNowrapSet;var brdColor=null;for(var i=0;i<inspected.childNodes.length;i++){if(inspected.childNodes[i].nodeType==1&&(inspected.childNodes[i].nodeName.toLowerCase()=="td"||inspected.childNodes[i].nodeName.toLowerCase()=="th")){if(!brdColor){brdColor=inspected.childNodes[i].style.borderColor;}
if(brdColor!=inspected.childNodes[i].style.borderColor){brdColor='';break;}}}
var _brdColor=brdColor?makeHexaColorCode(brdColor):'';util_safeSetFieldValue(this.tr_brdcolor,_brdColor);try{document.getElementById(this.tr_brdmonitor).style.backgroundColor=_brdColor;}catch(e){};var checked=true;for(var j=inspected.cells.length-1;j>=0;j--){checked=checked&&inspected.cells[j].tagName=="TH";if(!checked){break;}}
document.getElementById(this.tr_header).checked=checked;};function makeHexaColorCode(inputValue){var colorInHexa=/\#[abcdef0123456789]{6}/i;if(colorInHexa.test(inputValue)){return inputValue.toUpperCase();}
var colorInRGB=/rgb\((\d{1,3})\,\s{0,1}(\d{1,3})\,\s{0,1}(\d{1,3})\)/i;if(colorInRGB.test(inputValue)){var _digits="0123456789ABCDEF";function decimal2hexa(val){var result=_digits.substr(val&15,1);while(val>15){val>>=4;result=_digits.substr(val&15,1)+result;}
return result;}
var values=inputValue.match(colorInRGB);var result='#';for(var i=1;i<=3;i++){var _current=values[i];var _translated=decimal2hexa(_current);_translated=(_translated.length==1)?'0'+_translated:_translated;result+=_translated;}
return result.toUpperCase();}
return'';};TableRowPI.prototype.apply=TableRowPI_apply;TableRowPI.prototype.inspect=TableRowPI_inspect;window.KtmlPIObjects["tr"]=TableRowPI;