
var help_mode=false;finish_value="||Finish||";ok_value="||OK||";function init(){utility.window.setModal();if(is.ie){document.charset=opener.document.charset;}
var getvars=new QueryString();if(window.opener.ktmls){ktml=window.opener.ktmls[getvars.find('id')];}else{ktml=opener.ktml;}
document.body.innerHTML=lang_translatepage(document.body.innerHTML,ktml.config.UILanguage,window.topOpener);document.body.oncontextmenu=function(){return false;};editImagePath=ktml.getModuleProperty('filebrowser','editImagePath');folder=editImagePath.replace(/\/[^\/]*$/,'/');if(folder==editImagePath){folder='';}
folder='/'+folder;filename=editImagePath.replace(/^.*\//,'');editImageWidth='';editImageHeight='';editImageSize='';editImageDimChanged=false;keepResizeProportions=true;zCanvas=document.getElementById("image");zImage=DNDDom.getElement("theImage");zShadow=DNDDom.getElement("theShadow");zSelection=DNDDom.getElement("theSelection");zCropper=DNDDom.getElement("theCropper");zCropperImage=DNDDom.getElement("theCropperImage");set_buttons_state();getAndRenderImageDetails();renderImage();}
function userFriendlyErr(result){return utility.string.getInnerText(result);}
function set_buttons_state(){ktml.makeRequest('image',"checkcapabilities",{"folder":folder,"rel_filename":filename},function(result){if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
has_imaging=result.hasimg!='';setButtonState('btn_crop',result.crop);setButtonState('btn_resize',result.resize);setButtonState('btn_rotate_left',result.rotate);setButtonState('btn_rotate_right',result.rotate);setButtonState('btn_flip_vertically',result.flip);setButtonState('btn_flip_horizontally',result.flip);setButtonState('btn_blur',result.blur);setButtonState('btn_sharpen',result.sharpen);setButtonState('btn_contrast_more',result.contrast);setButtonState('btn_contrast_less',result.contrast);setButtonState('btn_brightness_more',result.brightness);setButtonState('btn_brightness_less',result.brightness);setButtonState('btn_compress',result.degrade);if(result.degrade&&!filename.match(/\.jp[eg]+$/i)){setButtonState('btn_compress',false);}});}
function setButtonState(btn_name,enabled){document.getElementById(btn_name).className=enabled?'':'btn_disabled';if(btn_name=="btn_undo"){document.getElementById("btn_finish").className=enabled?'':'btn_disabled';}}
function renderImage(){var imageContainer=document.getElementById('image');zImage=document.getElementById('theImage');var imageCropperElement=document.getElementById('theCropperImage');var imageLoadingContainer=document.getElementById('theImageLoading');var tdBox=utility.dom.getBox(document.getElementById("file_preview"));imageContainer.style.top=(tdBox.y-(is.ie?1:0))+"px";imageContainer.style.left=(tdBox.x-(is.ie?1:0))+"px";imageContainer.style.width=(tdBox.width-2)+"px";imageContainer.style.height=(tdBox.height-2)+"px";if(is.mozilla){zImage.style.display='none';}
ktml.makeRequest('image',"createpreview",{"folder":folder,"rel_filename":filename,'size':'large'},function(result){if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));window.setTimeout("window.close()",10);return;}
result=result[0];if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));window.setTimeout("window.close()",10);return;}
var tmpFolder=window.topOpener.ktml_location.server+ktml.getModuleProperty('media','UploadFolderUrl');var image=tmpFolder.replace(/(?:^\/|\/$)/g,'');image+=encodeURI(result.thumbnail);zImage.onload=function(){if(is.mozilla){zImage.style.display='block';}
zImage.onload=null;imageLoadingContainer.style.visibility='hidden';imageContainer.style.display='block';cropObj=new ImageCropper(document.getElementById('image'),null,document.getElementById('crop.width'),document.getElementById('crop.height'),document.getElementById('crop.x'),document.getElementById('crop.y'));origw=zImage.width;origh=zImage.height;}
zImage.src=image+'?size='+editImageSize+'&rand='+Math.random();imageCropperElement.src=image+'?size='+editImageSize+'&rand='+Math.random();});}
function getAndRenderImageDetails(){window.document.title=topOpener.translate("Image Editor")+' - '+filename;var imageDetailsContainer=document.getElementById('imageDetails');imageDetailsContainer.innerHTML=filename;var imageInfoContainerL1=document.getElementById('imageInfoL1');imageInfoContainerL1.innerHTML=topOpener.translate('Image Path:')+' '+editImagePath;ktml.makeRequest('image',"getfileinfo",{"folder":folder,"rel_filename":filename},function(result){if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;zoom('clear');renderImageDetails();});}
function renderImageDetails(){var imageDetailsContainer=document.getElementById('imageDetails');imageDetailsContainer.innerHTML=filename+' - '+editImageWidth+'x'+editImageHeight+' - '+shwoFriendlySize(editImageSize);var imageInfoContainerL2=document.getElementById('imageInfoL2');imageInfoContainerL2.innerHTML=topOpener.translate('Details:')+' '+editImageWidth+'x'+editImageHeight+' - '+shwoFriendlySize(editImageSize);}
function shwoFriendlySize(size){size/=1024;var ret=parseInt(size);if(ret<1){ret=1;}
return ret+' KB';}
function show(what){if(what!='crop'&&window.cropObj){cropObj.hide();}
document.getElementById('crop').style.display='none';document.getElementById('compress').style.display='none';document.getElementById('resize').style.display='none';if(what){document.getElementById('default_pi').style.display='none';document.getElementById(what).style.display='block';setButtonState('btn_finish',false);}else{document.getElementById('default_pi').style.display='block';}}
function click_resize(btn){if(btn.className!='btn_disabled'){document.getElementById('resize_width').value=editImageWidth;document.getElementById('resize_height').value=editImageHeight;show('resize');}}
function click_resize_constrain_proportions(btn){keepResizeProportions=btn.checked;}
function change_resize(what){if(!keepResizeProportions){return;}
if(what=='width'){var width=document.getElementById('resize_width').value;width=width.replace(/\D/g,'');document.getElementById('resize_width').value=width;var height=parseInt(width*editImageHeight/editImageWidth);document.getElementById('resize_height').value=height;}else{var height=document.getElementById('resize_height').value;height=height.replace(/\D/g,'');document.getElementById('resize_height').value=height;var width=parseInt(height*editImageWidth/editImageHeight);document.getElementById('resize_width').value=width;}}
function image_resize(){var width=document.getElementById('resize_width').value;var height=document.getElementById('resize_height').value;if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"resize",{"folder":folder,"rel_filename":filename,'width':width,'height':height,'keep_proportion':keepResizeProportions},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}
function click_crop(btn){if(btn.className!='btn_disabled'){show('crop');if(window.cropObj){cropObj.initialCrop();}}}
function image_crop(){var cropX=document.getElementById("crop.x").value;var cropY=document.getElementById("crop.y").value;var cropWidth=parseInt(document.getElementById("crop.width").value);var cropHeight=parseInt(document.getElementById("crop.height").value);var tmpWidth=document.getElementById('theImage').width;var tmpHeight=document.getElementById('theImage').height;var widthRatio=editImageWidth/tmpWidth;var heightRatio=editImageHeight/tmpHeight;show();var tmpObj={"folder":folder,"rel_filename":filename,'top':parseInt(cropY),'left':parseInt(cropX),'width':parseInt(cropWidth),'height':parseInt(cropHeight)};if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"crop",tmpObj,function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageDimChanged=true;editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();getAndRenderImageDetails();setButtonState('btn_undo',true);});}
function click_rotate(btn,angle){if(btn.className!='btn_disabled'){if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"rotate",{"folder":folder,"rel_filename":filename,'angle':angle},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageDimChanged=true;editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}}
function click_flip(btn,direction){if(btn.className!='btn_disabled'){if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"flip",{"folder":folder,"rel_filename":filename,'direction':direction},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}}
function click_blur(btn){if(btn.className!='btn_disabled'){if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"blur",{"folder":folder,"rel_filename":filename},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}}
function click_sharpen(btn){if(btn.className!='btn_disabled'){if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"sharpen",{"folder":folder,"rel_filename":filename},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}}
function click_contrast(btn,intensity){if(btn.className!='btn_disabled'){if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"contrast",{"folder":folder,"rel_filename":filename,'intensity':intensity},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}}
function click_brightness(btn,intensity){if(btn.className!='btn_disabled'){if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"brightness",{"folder":folder,"rel_filename":filename,'intensity':intensity},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}}
function click_compress(btn){if(btn.className!='btn_disabled'){show('compress');}}
function check_compress_ENTER(o,e){if(e.keyCode==13){image_compress();return false;}
return true;}
function image_compress(){var degradejpeg_procent=parseInt(document.getElementById('image_quality').value);if(degradejpeg_procent>=100||degradejpeg_procent<=0){var msg='Please enter a value between %d and %d.';msg=utility.string.sprintf(window.topOpener.translate(msg),1,99);alert(msg);return;}
if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"degrade",{"folder":folder,"rel_filename":filename,'degradejpeg_procent':degradejpeg_procent},function(result){utility.window.unblockInterface();if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',true);});}
function clickFinish(){if(document.getElementById('btn_finish').className=='btn_disabled'){return;}
if(window.cropObj){cropObj.hide();}
ktml.makeRequest('image',"deleteundo",{"folder":folder,"rel_filename":filename},function(result){if(window.opener.refreshSelectedImage){window.opener.refreshSelectedImage(folder,filename);if(is.mozilla){window.setInterval(function(){if(opener.closeMe){opener.closeMe=false;window.setTimeout('window.close()',1);}},100);}else{window.setTimeout('window.close()',1);}}else{var img=ktml.logic_getSelectedNode();var tmp=img.src.toString();tmp=tmp.replace(/\?.*$/,'');tmp+='?size='+editImageSize;img.src=tmp;if(editImageDimChanged){img.removeAttribute('width');img.removeAttribute('height');}
window.setTimeout('window.close()',1);}});}
function clickUndo(windowClosed){if(document.getElementById('btn_undo').className=='btn_disabled'){return;}
if(window.cropObj){cropObj.hide();}
utility.window.blockInterface();ktml.makeRequest('image',"undo",{"folder":folder,"rel_filename":filename},function(result){editImageDimChanged=false;utility.window.unblockInterface();if(windowClosed){window.setTimeout('utility.window.close()',1);return;}
if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
editImageWidth=result.width;editImageHeight=result.height;editImageSize=result.size;renderImage();renderImageDetails();show();setButtonState('btn_undo',false);});}
function clickCancel(){if(document.getElementById('btn_undo').className!='btn_disabled'){clickUndo(true);}
else{utility.window.close();}}