
FileList=function(ktml,container,target_path,select_file,options){KTStorage.add(this);var list_id=this.id;this.ktml=ktml;this.container=container;if(typeof(this.container)=="string"){this.container=document.getElementById(this.container);}
this.div=document.getElementById("files_list");this.div.setAttribute('has_context_menu','true');this.tim=null;utility.dom.attachEvent(this.div,'onscroll',function(){window.clearTimeout(file_list.tim);file_list.tim=window.setTimeout('file_list.onscroll()',50);});utility.dom.attachEvent(this.div,'onclick',function(){if(file_list.cancelClick){file_list.cancelClick=false;return false;}
file_list.selectChild("",true);file_list.trigger_event("onitemdeselect");});if(typeof(target_path)=="undefined")target_path="/";Object_weave_safe(this,options);this.path="";this.last_requested_path="";this.status=0;this.children=[];this.selection=[];if(typeof(window[this.type+"FileList"])!="undefined"){Object_weave(FileList.prototype,window[this.type+"FileList"].prototype);if(typeof(this.inittype)=="function"){this.inittype();}}
if(is.mozilla){this.div.addEventListener("DOMMouseScroll",function(e){file_list.onwheel(e);},true);}else{this.div.onmousewheel=function(e){file_list.onwheel(e);};}
select_file=select_file.replace(new RegExp("^.*\\/",""),"");this.list_path(target_path,this.filter,select_file);};FileList.prototype.onwheel=function(e){var o=utility.dom.setEventVars(e);utility.dom.stopEvent(o.e);var delta=is.ie?(o.e.wheelDelta>0?-1:+1):(o.e.detail>0?1:-1);delta*=137/2;this.div.scrollTop+=delta;if(is.mozilla){this.onscroll();}};ThumbnailThread=function(owner,tasks){KTStorage.add(this);this.owner=owner;this.tasks=tasks.replace(/^,+|,+$/gi,'').split(",");};ThumbnailThread.prototype.run=function(){var files=[];var id=this.id;for(var i=0;i<this.tasks.length;i++){if(!this.tasks[i])continue;file=KTStorage.get(this.tasks[i]);file.state="loading";utility.dom.classNameAdd(file.getElement("table").rows[0].cells[0],"loading");files.push(file.name);}
thumber.tasks=array_substract(thumber.tasks,this.tasks);thumber.currentWorkers++;files=files.join("|");ktml.makeRequest("image","createpreview",{folder:current_path,rel_filename:files,size:'small'},function(result){KTStorage.get(id).finalize(result);});};function array_substract(src,substract){var ret=[];var src=src.join(",");for(var i=0;i<substract.length;i++){var re=new RegExp(","+substract[i]+"|,"+substract[i]+"|"+substract[i]+"","i");src=src.replace(re,'');}
if(src!=""){src=src.split(",")
for(var i=0;i<src.length;i++){if(src[i]){ret.push(src[i])}}}
return ret;}
ThumbnailThread.prototype.finalize=function(result){thumber.currentWorkers--;var file=null;if(result&&result.error){result.thumbnail="ERROR";for(var i=0;i<this.tasks.length;i++){file=KTStorage.get(this.tasks[i]);if(!file){continue;}
utility.dom.classNameRemove(file.getElement("table").rows[0].cells[0],"loading");file.state="error";file.update(result);if(current_file==file.name){file.select();}}}else{for(var i=0;i<result.length;i++){file=file_list.getChildIndexByName(result[i].orig_filename);if(file==-1){continue;}
file=file_list.children[file];utility.dom.classNameRemove(file.getElement("table").rows[0].cells[0],"loading");file.state="loaded";file.update(result[i]);if(current_file==file.name){file.select();}}}
thumber.tasks=array_substract(thumber.tasks,this.tasks);file_list.onscroll();};ThumbnailCreator=function(){KTStorage.add(this);this.tasks=[];this.timeouts=[];this.pendings=[];if(is.ie){this.maxWorkers=4;this.maxWorkerLoad=4;}else{this.maxWorkers=4;this.maxWorkerLoad=4;}
this.currentWorkers=0;};ThumbnailCreator.prototype.add=function(id){this.tasks.push(id);};ThumbnailCreator.prototype.stop=function(){for(var z in this.timeouts){window.clearTimeout(this.timeouts[z]);var file_ids=this.pendings[z].split(",");this.tasks=array_substract(this.tasks,file_ids);for(var j=0;j<file_ids.length;j++){KTStorage.get(file_ids[j]).state="canceled";}}
this.timeouts=[];this.pendings=[];this.tasks=[];};ThumbnailCreator.prototype.start=function(){var task_list=[];var file=null;var current=this.currentWorkers;var offset=0;for(var i=0;i<this.tasks.length;i++){file=KTStorage.get(this.tasks[i]);if(file.state=="loaded"||file.state=="loading"||file.state=="error"){continue;}
if((current+offset)>=this.maxWorkers){break;}
task_list.push(this.tasks[i]);if((i+1)%this.maxWorkerLoad==0){offset++;thumber.work(task_list);task_list=[];}}
if(task_list.length&&(current+offset)<this.maxWorkers){thumber.work(task_list);}};ThumbnailCreator.prototype.work=function(task_list){var tim_id='tim_'+Math.random();var file=null;var psize=0;var file_list=[];for(var j=0;j<task_list.length;j++){file=KTStorage.get(task_list[j]);file.state="loading";file_list.push(task_list[j]);}
this.pendings[tim_id]=file_list.join(",");this.timeouts[tim_id]=window.setTimeout('thumber.late_work("'+tim_id+'", "'+this.pendings[tim_id]+'")',100);};ThumbnailCreator.prototype.late_work=function(tim_id,tasks){delete this.timeouts[tim_id];var worker=new ThumbnailThread(this.id,tasks);worker.run();};FileList.prototype.onscroll=function(){window.clearTimeout(this.tim);thumber.stop();this.tim=null;var st=this.div.scrollTop;var ot,i;for(i=0;i<this.children.length;i++){if(!this.children[i].revealed){ot=this.children[i].getElement("table").offsetTop;if((ot<st+274+137)&&(ot>st-137)){if(this.children[i].image){if(this.children[i].result.thumbnail=="notexist"){if(this.children[i].state!="loading"){thumber.add(this.children[i].id);}}else if(this.children[i].result.thumbnail=="ERROR"||this.children[i].state=="error"){}else{this.children[i].update();}}else{this.children[i].update();}}}}
thumber.start();};FileList.prototype.file_exists=function(file_name){return this.get_item(file_name);};FileList.prototype.trigger_event=function(event_name){var evfn;var args=[];for(var i=1;i<arguments.length;i++){args.push(FileList.prototype.trigger_event.arguments[i]);}
evfn=this[event_name];if(typeof(evfn)=="function"){evfn.apply(this,args);}};FileList.toggle_item=function(elem,e){var i,el,item,o,idx,minIdx=100000,maxIdx=-1,startIdx,endIdx;single=true;el=elem;while(el.tagName.toLowerCase()!="body"&&el.getAttribute("item_id")==null){el=el.parentNode;}
if(el.getAttribute("item_id")){item=KTStorage.get(el.getAttribute("item_id"));if(e.ctrlKey&&!e.shiftKey){single=false;}
var list=KTStorage.get(item.list_id);if(e.shiftKey){idx=list.getChildIndexByName(item.name);for(i=0;i<list.children.length;i++){if(!list.children[i].selected){continue;}
minIdx=Math.min(minIdx,i);maxIdx=Math.max(maxIdx,i);}
list.deselectAll();startIdx=Math.min(idx,idx>maxIdx?maxIdx:idx);endIdx=Math.max(idx,idx<minIdx?minIdx:maxIdx);for(i=startIdx;i<=endIdx;i++){list.children[i].select(endIdx==startIdx,endIdx>startIdx);}
if(endIdx>startIdx){list.trigger_event("onitemselect",list.children[i-1].name)}}else{if(e.ctrlKey&&item.selected){item.deselect();if(list.children.length==1){list.trigger_event("onitemselect",list.children[0].name)}}else{list.selectChild(item.name,single);}}}
utility.dom.stopEvent(e);};FileList.prototype.list_path=function(target_path,filter,select_file,block){var list_id=this.id;if(typeof(filter)=="undefined"||filter=="")filter=this.filter;if(typeof(target_path)=="undefined"||target_path=="")target_path=this.path;this.last_requested_path=target_path;if(this.path!=target_path||this.filter!=filter){this.filter=filter;this.status=0;this.children=[];this.selection=[];if(FLS){document.body.appendChild(FLS);FLS.innerHTML="<div></div>";}
this.div.innerHTML='<div class="loading">'+trans(i18n.LOADING)+'</div>';var params={folder:target_path,submode:browse_submode,what:"files",ignore_thumbnail_errors:"true",filter:this.filter};this.ktml.makeRequest("folder","read",params,function(result){if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
KTStorage.get(list_id).receive_path(result,target_path,function(){KTStorage.get(list_id).onscroll();KTStorage.get(list_id).selectChild(select_file);if(typeof(block)=="function")block();});});}};FileList.prototype.receive_path=function(result,target_path,block){if(this.last_requested_path!=target_path){return;}
this.path=target_path;if(this.children.length==0){this.div.innerHTML=trans(i18n.NO_FILES);}
this.html='';for(i=0;i<result.length;i++){this.addChild(result[i].name,result[i]);}
if(this.children.length!=0&&browse_submode!="templates"){this.div.innerHTML=this.html;for(var i=0;i<this.children.length;i++){this.children[i].div=document.getElementById(this.children[i].id);if(this.children[i].type=="Template"){KT_Tooltips.attach_single(this.children[i].getElement("table"));}}}
this.trigger_event("onload",target_path,result);if(typeof(block)=="function")block();if(FLS){this.div.appendChild(FLS);FLS.innerHTML="<div></div>";}};FileList.prototype.upload=function(result,block){};FileList.prototype.get_item=function(name){var idx;idx=this.getChildIndexByName(name);if(idx>=0){return this.children[idx];}
return false;};FileList.prototype.del=function(files,block){var i,dir,file;if(typeof(files)=="string")files=[files];files_left_to_delete=files.length;files_deleted=[];for(i=0;i<files.length;i++){dir=files[i].replace(new RegExp("[^\\/]+$",""),"");file=files[i].replace(new RegExp("^.*\\/",""),"");this.ktml.makeRequest("file","delete",{"submode":browse_submode,"filename":dir+file},function(result){files_deleted.push(result);if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
if(files_deleted.length==files_left_to_delete){block();}});}};FileList.prototype.before_op=function(files,block){this.opfiles=files;this.optoreceive=files.length;this.opreceived=0;this.operr=[];this.opblock=block;utility.window.blockInterface();};FileList.prototype.op=function(op,files,destdir,block){var srcdir;var list_id=this.id;if(typeof(destdir)=="undefined"||destdir=="")destdir=this.path;if(typeof(files)=="string")files=[files];srcdir=files[0].replace(/[^\/]+$/,"");if(op=="cut"&&srcdir==destdir){block([]);return;}
this.ktml.makeRequest("folder","read",{"folder":destdir,"submode":browse_submode,"what":"files","filter":browse_filter},function(result){if(typeof result=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
var names,newnames,i,cnt;var filename,tmpsrc,tmpdest;names=[];newnames=[];for(i=0;i<result.length;i++){names.push(result[i].name);}
Array_each(files,function(file){filename=file.replace(new RegExp("^.*\\/",""),"");newname=filename;cnt=1;while(Array_indexOf(names,newname)!=-1||Array_indexOf(newnames,newname)!=-1){newname="Copy "+(cnt>1?"("+cnt+") ":"")+"of "+filename;cnt++;}
newnames.push(newname);});var list=KTStorage.get(list_id);list.before_op(files,block);for(i=0;i<files.length;i++){tmpsrc=files[i];tmpdest=destdir;list.op_one(op,tmpsrc,tmpdest,function(result,s,d){list.op_receive(result,s,d);});}});};FileList.prototype.op_one=function(op,filename,newname,block){var was_cut=false;if(op=="cut"){op="copy";was_cut=true;}
ktml.makeRequest("file",op,{"filename":filename,"submode":browse_submode,"new_filefolder":newname},function(op_result){if(typeof(op_result)=='object'&&op_result.error){if(typeof block=="function")block(op_result,filename,newname);return;}
if(was_cut){ktml.makeRequest("file","delete",{"submode":browse_submode,"filename":filename},function(delete_result){if(typeof block=="function")block(op_result,filename,newname);});}else{if(typeof block=="function")block(op_result,filename,newname);}});};FileList.prototype.op_receive=function(result,src,dest){var i,s,tmp;this.opreceived++;if(typeof result=='object'&&result.error){this.operr.push({"message":result.error.message,"file":src});}
if(this.opreceived==this.optoreceive){utility.window.unblockInterface();if(typeof this.opblock=="function")this.opblock(this.operr);}};FileList.prototype.markforcut=function(item,replacemarks){var items=[],crt;if(typeof replacemarks=="undefined")replacemarks=false;if(typeof item=="string"){items.push(item);}else{items=item;}
if(typeof items=="object"&&items.length){for(i=0;i<this.children.length;i++){crt=this.children[i];if(Array_indexOf(items,crt.name)!=-1||Array_indexOf(items,crt.path)!=-1){crt.markforcut();}else if(replacemarks){crt.unmarkforcut();}}}};FileList.prototype.selectAll=function(){for(i=0;i<this.children.length;i++){var was_selected=this.children[i].selected;if(!was_selected){this.children[i].select(false,true);this.trigger_event("onitemselect",this.children[i].name,true);}}
if(this.children.length){this.trigger_event("onitemselect",this.children[i-1].name)}};FileList.prototype.deselectAll=function(){this.selectChild("",true,true);this.trigger_event("onitemdeselect","")};FileList.prototype.selectChild=function(name,single,silent){if(typeof single=="undefined")single=false;if(typeof silent=="undefined")silent=false;var i;if(single){for(i=0;i<this.children.length;i++){if(name!=this.children[i].name){this.children[i].deselect(true);}}}
for(i=0;i<this.children.length;i++){if(name==this.children[i].name){var was_selected=this.children[i].selected;this.children[i].select(single,silent);if(was_selected){this.trigger_event("onitemselect",name,silent);}}}};FileList.prototype.getChildIndexByName=function(name){var i;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){return i;}}
return-1;};FileList.prototype.addChild=function(name,result){var i,tmp,added,new_child,newnoext,crtnoext;tmp=this.div;if(this.children.length==0){tmp.innerHTML="";}
new_child=new FileListItem(this,result);this.html+=new_child.html;this.children.push(new_child);if(browse_submode=="templates"){tmp.appendChild(new_child.div);}
return new_child;};FileList.prototype.removeChild=function(name){var i,tmp;name=name.replace(new RegExp("^.*\\/",""),"");tmp=this.div;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){tmp.removeChild(this.children[i].div);this.children.splice(i,1);if(this.children.length==0){this.div.innerHTML=trans(i18n.NO_FILES);;}
return;}}};FileList.prototype.replaceChild=function(){};FileList.prototype.refreshChild=function(){};FileList.prototype.dispose=function(){for(i=0;i<this.children.length;i++){file_list.children[i].dispose();}};FileList.prototype.clear=function(){this.dispose();this.path="";this.last_requested_path="";this.status=0;this.children=[];this.selection=[];this.div.innerHTML="";};FilesFileList=function(){};FilesFileList.prototype.inittype=function(){};TemplatesFileList=function(){};TemplatesFileList.prototype.inittype=function(){};FileListItem=function(list,result){var image,table;this.selected=false;this.markedforcut=false;this.list_id=list.id;this.name=result.name;this.path=list.path+result.name;if(list.type=="Files"){if(isImage(this.name)){this.type="Image";}else{this.type="File";}}
else{this.type="Template";}
if(typeof window[this.type+"FileListItem"]!="undefined"){Object_weave(FileListItem.prototype,window[this.type+"FileListItem"].prototype);if(typeof this.inittype=="function"){this.inittype(result);}}};FileListItem.prototype.setDetails=function(result){var s="";for(var i in result){s+=i+": "+result[i]+"\n";}
alert(s)};FileListItem.prototype.getElement=function(el){return document.getElementById(this[el+"_id"]);};FileListItem.prototype.update=function(result){if(typeof result=='undefined'){result=this.result;}else{this.result=result;}
var table=document.getElementById(this.table_id);if(typeof result=='object'&&result.error){table.rows[0].cells[0].innerHTML='<div class="server_error">'+result.error.message.replace(/\.\s+/gi,".<br>")+'</div>';table.title=result.error.message.replace(/\.\s+/gi,".\r\n");KT_Tooltips.attach_single(table);return;}
var title=this.name;this.size=parseInt(result.size);title+='\n'+trans(i18n.SIZE)+': '+showFriendlySize(this.size);if(this.image||this.icon){this.revealed=true;var img=document.getElementById(this.img_id);if(!img){table.rows[0].cells[0].innerHTML='<img onmousedown="return false" id="'+this.id+'_img"/>';img=document.getElementById(this.img_id);}
var new_path='';if(this.image){if(result.thumbnail!="ERROR"&&result.thumbnail!="notexist"){this.width=parseInt(result.width);this.height=parseInt(result.height);title+='\n'+trans(i18n.DIMENSIONS)+' '+this.width+' x '+this.height;var scale=scaleDimensions(this.width,this.height);img.width=scale.width;img.height=scale.height;new_path=currentUploadFolder+encodeURI(result.thumbnail)+'?size='+this.size;this.image=new_path;}else{new_path=this.image;}}else if(this.icon){new_path=this.icon;}
new_path=new_path.replace(/\s/gi,'%20');img.src=new_path;}
table.title=title;KT_Tooltips.attach_single(table);};FileListItem.prototype.select=function(doscroll,silent){if(this.state=="loading"){return;}
var idx,scrollto;if(typeof(doscroll)=="undefined"){doscroll=true;}
if(typeof(silent)=="undefined"){silent=false;}
item_selection_type="file";if(!this.selected){this.selected=true;utility.dom.classNameAdd(this.div,"thumbnail_selected");KTStorage.get(this.list_id).trigger_event("onitemselect",this.name,silent);}
if(doscroll){idx=KTStorage.get(this.list_id).getChildIndexByName(this.name);var item_height=this.getElement("table").offsetHeight+(is.ie?4:0);var st=KTStorage.get(this.list_id).div.scrollTop;scrollto=Math.floor(idx/4)*item_height;if(st+2*item_height<scrollto+item_height){KTStorage.get(this.list_id).div.scrollTop=scrollto-item_height;if(is.mozilla){KTStorage.get(this.list_id).onscroll()}}
if(st>scrollto){KTStorage.get(this.list_id).div.scrollTop=scrollto;if(is.mozilla){KTStorage.get(this.list_id).onscroll()}}}};FileListItem.prototype.deselect=function(silent){if(this.selected){this.selected=false;utility.dom.classNameRemove(this.div,"thumbnail_selected");KTStorage.get(this.list_id).trigger_event("onitemdeselect",this.name,silent);item_selection_type="none";}};FileListItem.prototype.markforcut=function(){if(!this.markedforcut){this.markedforcut=true;utility.dom.classNameAdd(this.div,"thumbnail_cut");}};FileListItem.prototype.unmarkforcut=function(){if(this.markedforcut){this.markedforcut=false;utility.dom.classNameRemove(this.div,"thumbnail_cut");}};FileListItem.prototype.setName=function(){};FileListItem.prototype.setImage=function(thumbnail,rel_filename,width,height){var img=document.getElementById(this.img_id);if(!img){table.rows[0].cells[0].innerHTML='<img onmousedown="return false" id="'+this.id+'_img"/>';}
img=document.getElementById(this.img_id);if(this.thumbnail){if(this.thumbnail!="ERROR"&&this.thumbnail!="notexist"){this.width=parseInt(width);this.height=parseInt(height);var scale=scaleDimensions(this.width,this.height);img.width=scale.width;img.height=scale.height;var new_path=currentUploadFolder+rel_filename;new_path=new_path.replace(/\/\//gi,'/').replace(/\s/gi,'%20');img.src=new_path;}else{img.src=this.display_image;}}else{img.src=this.display_image;}};FileListItem.prototype.setState=function(state){var img=this.getElement("img");switch(state){case"LOADING":utility.dom.classNameAdd(this.getElement("table").rows[0].cells[0],"loading");if(img){img.style.visibility="hidden";}
break;case"READY":if(img){this.getElement("img").style.visibility="";}
utility.dom.classNameRemove(this.getElement("table").rows[0].cells[0],"loading");break;case"UPLOADING":break;}};FileListItem.prototype.dispose=function(){this.img=null;this.table=null;this.div=null;};function scaleDimensions(width,height){var ret={width:0,height:0};var ratio=width/height;var w=width;var h=height;if(w>100||h>100){if(w>h){w=100;h=parseInt(w/ratio);}else{h=100;w=parseInt(h*ratio);}}
ret.width=w;ret.height=h;return ret;};FileFileListItem=function(){};FileFileListItem.prototype.inittype=function(result){KTStorage.add(this);this.result=result;this.revealed=false;this.size=result.size;if(result.thumbnail){if(result.thumbnail=="ERROR"||result.thumbnail=="notexist"){this.image=result.name;}else{this.image=result.thumbnail+'?size='+result.size;}}else{var image='';if(this.name.match(/\.(avi|wmv|asf|txt|swf|mov|pdf)$/i)){var ext=RegExp.$1;if(ext=='wmv'||ext=='asf'){ext='avi';}
image=window.topOpener.KtmlRoot+'modules/filebrowser/img/'+ext+'.gif';}else{image=window.topOpener.KtmlRoot+'modules/filebrowser/img/unknown.gif';}
this.icon=image;}
var cut_name=this.name;if(cut_name.length>14){var parts=cut_name.match(/(.*?)(\.?[^\.]*)$/);cut_name2=parts[1].substring(0,11)+"..."+parts[2];if(cut_name2.length<cut_name.length){cut_name=cut_name2;}}
this.html='<span id="'+this.id+'" item_id="'+this.id+'" has_context_menu="true">';this.html+='<table class="thumbnail_container" onclick="FileList.toggle_item(this, event)" ondblclick="FileList.toggle_item(this, event);insert_selected(this, event)" id="'+this.id+'_table">\
   <tr>\
    <td class="thumbnail_box"><div style="width:100px;height:100px;"></div></td>\
   </tr>\
   <tr>\
    <td><div class="thumbnail_item_name"><span tabIndex="1">'+cut_name+'</span></div></td>\
   </tr>\
  </table>';this.html+='</span>';this.table_id=this.id+'_table';this.img_id=this.id+'_img';};ImageFileListItem=function(){};ImageFileListItem.prototype.inittype=FileFileListItem.prototype.inittype;TemplateFileListItem=function(){};TemplateFileListItem.prototype.inittype=function(result){KTStorage.add(this);var image,tmp,href='javascript:;';this.size=result.size;var title=this.name;title+='\n'+trans(i18n.SIZE)+' '+showFriendlySize(this.size);image=window.topOpener.KtmlRoot+'modules/filebrowser/img/txt.gif';this.template_content=result.template_content;this.div=document.createElement("span");this.div.setAttribute("item_id",this.id);this.div.setAttribute("has_context_menu","true");;this.revealed=true;this.div.innerHTML='<table class="thumbnail_container" title="'+title+'" onclick="FileList.toggle_item(this, event)" ondblclick="FileList.toggle_item(this, event);insert_selected(this, event)"  id="'+this.id+'_table">\
   <tr>\
    <td class="thumbnail_box"><div class="template_thumbnail">'+this.template_content+'</div></td>\
   </tr>\
   <tr>\
    <td><div class="thumbnail_item_name"><a href="'+href+'">'+this.name+'</a></div></td>\
   </tr>\
  </table>';this.table_id=this.id+'_table';this.table=this.div.getElementsByTagName('table')[0];};