
__global_clicked=false;FolderTree=function(ktml,container,target_path){KTStorage.add(this);var this_id=this.id;this.ktml=ktml;this.container=container;if(typeof(this.container)=="string"){this.container=document.getElementById(this.container);}
this.div=utility.dom.getElementsByClassName(this.container,"fl_container","div")[0];this.div.innerHTML='';this.div.tree_id=this_id;this.container.tree_id=this_id;utility.dom.attachEvent(this.container,'onclick',function(){if(__global_clicked){__global_clicked=false;return false;};KTStorage.get(this_id).select_path("/");});if(typeof(target_path)=="undefined"){target_path="/";}
target_path=target_path.replace(/^\/+/,"/");this.selected_path="";this.root=new FolderTreeItem(this.id,false,"/");this.div.appendChild(this.root.div);this.select_path(target_path);};FolderTree.prototype.trigger_event=function(event_name){var evfn;var args=new Array(arguments.length-1);for(var i=1;i<arguments.length;i++){args[i-1]=arguments[i];}
evfn=this[event_name];if(typeof(evfn)=="function"){evfn.apply(this,args);}};FolderTree.toggle_node=function(elem,e){utility.dom.stopEvent(e);var node=KTStorage.get(elem.parentNode.parentNode.getAttribute("item_id"));if(node.isOpen){node.close();}else{if(node.subfolders>0){node.open();}else{node.setOpen();}}
return false;};FolderTree.select_node=function(elem,e){var node=KTStorage.get(elem.parentNode.parentNode.getAttribute("item_id"));utility.dom.stopEvent(e);KTStorage.get(node.tree_id).select_path(node.path);};FolderTree.prototype.path_to_node=function(target_path,block){var crt,i,parts,idx;crt=this.root;parts=target_path.split("/");for(i=1;i<parts.length;i++){if(crt.path<target_path){idx=crt.getChildIndexByName(parts[i]);if(idx>=0){crt=crt.children[idx];}else{return crt;}}}
return crt;};FolderTree.prototype.open_path=function(target_path,block){target_path=target_path.replace(/^\/+/,"/");var crt,i,parts,idx;crt=this.root;parts=target_path.split("/");for(i=1;i<parts.length;i++){if(crt.isOpen){if(crt.path<target_path){idx=crt.getChildIndexByName(parts[i]);if(idx>=0){crt=crt.children[idx];}else{return;}}}else{tree=this;crt.open(function(path){tree.open_path(target_path,block);});return;}}
if(typeof(block)=="function")block(crt);};FolderTree.prototype.close_path=function(target_path,block){var node;node=this.path_to_node(target_path);node.close();if(typeof(block)=="function")block(node);};FolderTree.prototype.select_path=function(target_path,block){var parts,toselect,tree;tree=this;target_path=target_path.replace(/^\/+/,"/");if(target_path=="/"){this.open_path("/",function(){tree.root.select();if(typeof(block)=="function")block();});}else{parts=target_path.split("/");toselect=parts[parts.length-2];parts.splice(parts.length-2,1);this.open_path(parts.join("/"),function(node){node.selectChild(toselect);var idx;idx=node.getChildIndexByName(toselect);if(typeof(block)=="function")block();});}};FolderTree.prototype.cd_up=function(){this.select_path(this.selected_path.replace(/[^\/]+\/$/,""));};FolderTree.prototype.mkdir=function(name,block){var tree,node,toadd;tree=this;node=this.path_to_node(this.selected_path);toadd=this.selected_path+name+"/";this.ktml.makeRequest("folder","create",{"folder":toadd,"submode":browse_submode},function(result){if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));if(typeof(block)=="function")block();return;}
if(node.childrenStatus>1){node.addChild(name,{"subfolders":0,"allfiles":0});node.setDetails({"subfolders":node.subfolders+1,"allfiles":node.allfiles,"filteredfiles":node.filteredfiles});}else{node.setDetails({"subfolders":node.subfolders+1,"allfiles":node.allfiles,"filteredfiles":node.filteredfiles});}
if(typeof(block)=="function")block();});};FolderTree.prototype.rmdir=function(path,block){var tree,node,toadd,parent;if(path==""){path=this.selected_path;}
if(path=="/")return;tree=this;node=this.path_to_node(this.selected_path);tree.ktml.makeRequest("folder","delete",{"folder":path,"submode":browse_submode},function(result){if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
parent=node.parent;parent.removeChild(node.name);parent.select();parent.setDetails({"subfolders":parent.subfolders-1,"allfiles":parent.allfiles,"filteredfiles":parent.filteredfiles});if(typeof(block)=="function")block();});};FolderTree.prototype.markforcut=function(item){node=this.path_to_node(item);node.markforcut();};FolderTree.prototype.dispose=function(){this.root.dispose();this.div=null;this.container=null;};FolderTreeItem=function(tree_id,parent,path){KTStorage.add(this);this.tree_id=tree_id;this.parent=parent;this.path=path;var tmparr=this.path.split("/");this.name=tmparr[tmparr.length-2];this.type="Folder";this.isOpen=0;this.childrenStatus=0;this.children=[];this.subfolders=0;this.allfiles=0;var str,tmp,tmp2,txt,w,max_width;tmp=document.createElement("div");txt=(this.path=="/")?"Root":this.name;tmp2=document.createElement("span");tmp2.innerHTML=txt;document.body.appendChild(tmp2);w=utility.dom.getBox(tmp2).width+5;document.body.removeChild(tmp2);str='<div class="fl_item"'+(this.path=="/"?' style="display:none"':'')+'>';if(this.path!="/"){str+='<div class="img"><img src="img/fl_none.gif"/></div>';}
str+='<a';str+=' ondblclick="FolderTree.toggle_node(this, event)"';str+=' onclick="preventQuickDeleteFlag = false; return FolderTree.select_node(this, event)">'+'<div class="img"><img src="img/fl_folder0.gif"/></div><span style="width: '+w+'px">'+txt+'</span></a>';str+='</div>';tmp.innerHTML=str;tmp.className="fl_item_container";tmp.style.width=(w+47)+"px";tmp.path=this.path;this.div=tmp;this.div.setAttribute("item_id",this.id);this.div.setAttribute("has_context_menu","true");;};FolderTreeItem.prototype.setOpen=function(val){this.isOpen=val;this.setPlusMinus();};FolderTreeItem.prototype.getChildIndexByName=function(name){var i;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){return i;}}
return-1;};FolderTreeItem.prototype.open=function(block){var tmp;this.setOpen(1);if(this.childrenStatus>1){if(this.children.length>0){tmp=utility.dom.getElementsByClassName(this.div,"fl_item_children","div")[0];utility.dom.showElem(tmp);KTStorage.get(this.tree_id).trigger_event("onnodeopen",this.path);}}
if(this.childrenStatus<=1){this.getChildren(block);}};FolderTreeItem.prototype.close=function(block){var tmp;if(this.path=="/")return;if(this.childrenStatus>1&&this.children.length>0){tmp=utility.dom.getElementsByClassName(this.div,"fl_item_children","div")[0];utility.dom.hideElem(tmp);KTStorage.get(this.tree_id).trigger_event("onnodeclose",this.path);}
this.setOpen(0);};FolderTreeItem.prototype.getChildren=function(block){var tmp;var node=this;this.childrenStatus=1;tmp=document.createElement("div");tmp.className="fl_item_children loading";tmp.innerHTML="<span style='padding-left: 24px'>"+trans(i18n.LOADING)+"</span>";this.div.appendChild(tmp);KTStorage.get(this.tree_id).ktml.makeRequest("folder","read",{"folder":node.path,"submode":browse_submode,"what":"folders","filter":browse_filter},function(result){node.receiveChildren(result,block);});};FolderTreeItem.prototype.receiveChildren=function(result,block){var i;if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
for(i=0;i<result.length;i++){this.addChild(result[i].name,result[i]);}
if(this.children.length==0){tmp=utility.dom.getElementsByClassName(this.div,"fl_item_children","div")[0];this.div.removeChild(tmp);}
this.subfolders=this.children.length;this.setPlusMinus();KTStorage.get(this.tree_id).trigger_event("onnodeopen",this.path);this.childrenStatus=2;node=this;if(typeof(block)=="function")block(node.path);this.childrenStatus=3;};FolderTreeItem.prototype.addChild=function(name,result){var i,tmp,added,new_child;tmp=utility.dom.getElementsByClassName(this.div,"fl_item_children","div")[0];if(!tmp){tmp=document.createElement("div");tmp.className="fl_item_children";this.div.appendChild(tmp);}
if(this.children.length==0){tmp.innerHTML="";}
new_child=new FolderTreeItem(this.tree_id,this,this.path+name+"/");if(typeof(result)=="object"){new_child.setDetails(result);}
for(i=0;i<this.children.length;i++){if(name.toLowerCase()<this.children[i].name.toLowerCase()){this.children.splice(i,0,new_child);tmp.insertBefore(new_child.div,this.children[i+1].div);added=true;break;}}
if(!added){this.children.push(new_child);tmp.appendChild(new_child.div);}
return new_child;};FolderTreeItem.prototype.removeChild=function(name){var i,tmp;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){tmp=utility.dom.getElementsByClassName(this.div,"fl_item_children","div")[0];tmp.removeChild(this.children[i].div);this.children.splice(i,1);if(this.children.length==0){this.div.removeChild(tmp);}
return;}}};FolderTreeItem.prototype.selectChild=function(name,block){var idx;idx=this.getChildIndexByName(name);if(idx>=0){this.children[idx].select();}
if(typeof(block)=="function")block(path);};FolderTreeItem.prototype.select=function(){var tmp,node,a,img;var idx,scrollto;var tree=KTStorage.get(this.tree_id);if(tree.selected_path!=""){node=tree.path_to_node(tree.selected_path);node.deselect();}
item_selection_type="folder";tmp=utility.dom.getElementsByClassName(this.div,"fl_item","div")[0];if(tmp){utility.dom.classNameAdd(tmp,"fl_selected");a=tmp.getElementsByTagName("a")[0];img=a.getElementsByTagName("img")[0];img.src="img/fl_folder1.gif";}
tree.selected_path=this.path;if(this!=tree.root){var c,cbox,d,dbox,buffer;buffer={x:20,y:16};c=tree.div.parentNode;d=utility.dom.getElementsByClassName(this.div,"fl_item","div")[0];cbox=utility.dom.getBox(c);dbox=utility.dom.getBox(d);if(c.scrollTop+cbox.height+cbox.y-buffer.y<dbox.y+dbox.height){c.scrollTop=dbox.y+dbox.height-(cbox.height+cbox.y-buffer.y);}
if(c.scrollTop+cbox.y>dbox.y){c.scrollTop=dbox.y-cbox.y}
if(c.scrollLeft+cbox.width+cbox.x-buffer.x<dbox.x+dbox.width){c.scrollLeft=dbox.x+dbox.width-(cbox.width+cbox.x-buffer.x);}
if(c.scrollLeft+cbox.x>dbox.x+38){c.scrollLeft=dbox.x+38-cbox.x;}}
tree.trigger_event("onnodeselect",this.path);};FolderTreeItem.prototype.deselect=function(){var tmp,a,img;tmp=utility.dom.getElementsByClassName(this.div,"fl_item","div")[0];if(tmp){utility.dom.classNameRemove(tmp,"fl_selected");a=tmp.getElementsByTagName("a")[0];img=a.getElementsByTagName("img")[0];img.src="img/fl_folder0.gif";}
KTStorage.get(this.tree_id).trigger_event("onnodedeselect",this.path);item_selection_type="none";return;};FolderTreeItem.prototype.dispose=function(){for(var i=0;i<this.children.length;i++){this.children[i].dispose();}
this.div=null;};FolderTree.prototype.op_one=function(op,src,block){var path=this.selected_path;if(op=="cut")op="move";this.ktml.makeRequest("folder",op,{"src":src,"dest":path},function(result){if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
if(typeof(block)=="function")block(result,src);});};FolderTreeItem.prototype.markforcut=function(){if(!this.markedforcut){this.markedforcut=true;utility.dom.classNameAdd(this.div,"thumbnail_cut");}};FolderTreeItem.prototype.unmarkforcut=function(){if(this.markedforcut){this.markedforcut=false;utility.dom.classNameRemove(this.div,"thumbnail_cut");}};FolderTreeItem.prototype.setDetails=function(result){this.subfolders=Number(result.subfolders);this.allfiles=Number(result.allfiles);this.filteredfiles=Number(result.filteredfiles);this.div.getElementsByTagName("a")[0].title=this.subfolders+" "+topOpener.translate("subfolders")+"\r\n"+this.filteredfiles+" "+topOpener.translate("files");KT_Tooltips.attach_single(this.div.getElementsByTagName("a")[0]);this.setPlusMinus();};FolderTreeItem.prototype.setPlusMinus=function(){var tmp,tmparr;if(this.path=="/")return;tmp=utility.dom.getElementsByClassName(this.div,"fl_item","div")[0];tmp=tmp.getElementsByTagName("img")[0];if(this.children.length==0&&this.subfolders==0){tmp.parentNode.onclick=function(){};tmp.src="img/fl_none.gif";}else{tmp.parentNode.onclick=function(event){FolderTree.toggle_node(this,event);__global_clicked=true;return false;};if(this.isOpen){tmp.src="img/fl_minus.gif";}else{tmp.src="img/fl_plus.gif";}}};