
function TablePI(owner){this.owner=owner;this.props='id,props_simple,props_advanced,props_simple_btn,props_advanced_btn,'+'width,height,cellpadding,cellspacing,'+'border,align,brdcolor,valign,bgimage,bgcolor,bgimage_browse,'+'caption,header,footer,summary';this.props=this.props.split(",");for(var i=0;i<this.props.length;i++){this["ctrl_"+this.props[i]]="Properties_table_"+this.props[i]+"_"+this.owner.name;}
var idx=this.owner.toolbar.indexOfName('insert_image');if(idx<0){document.getElementById(this.ctrl_bgimage_browse).style.visibility="hidden";}};function TablePI_apply(propName,propValue){var inspected=this.owner.inspectedNode;if(propValue!=''&&propValue!='false'){propValue=String(propValue);propValue=propValue.replace(/'/g,"\\'");switch(propName){case"bgimage":document.getElementById(this.ctrl_bgimage).value=decodeURI(util_removeSiteNameFromHREF(this.owner,propValue.replace(/\?size=\d*$/,'')));this.owner.inspectedNode.style.backgroundImage='url('+encodeURI(propValue)+')';break;case"bgColor":this.owner.inspectedNode.style.backgroundColor=propValue;try{document.getElementById(this.table_bgmonitor).style.backgroundColor=propValue;}catch(e){}
break;case"borderColor":this.owner.inspectedNode.style.borderStyle="solid";this.owner.inspectedNode.style.borderWidth="1px";this.owner.inspectedNode.style.borderColor=propValue;try{document.getElementById(this.table_brdmonitor).style.backgroundColor=propValue;}catch(e){}
var rows=this.owner.inspectedNode.rows;for(var j=0;j<rows.length;j++){for(var i=0;i<rows[j].cells.length;i++){rows[j].cells[i].setAttribute("borderColor",propValue);rows[j].cells[i].style.borderStyle='solid';rows[j].cells[i].style.borderWidth='1px';rows[j].cells[i].style.borderColor=propValue;}}
break;case"border":this.owner.inspectedNode.border=parseInt(propValue,10);if(propValue=='0'){if(this.owner.viewInvisibles){if(is.ie){setTimeout("try{ktmls["+this.owner.counter+"].utils_makeTableCallback(ktmls["+this.owner.counter+"].inspectedNode, ktmls["+this.owner.counter+"].utils_makeOutline);}catch(e){}",50);}else{this.owner.utils_makeTableCallback(this.owner.inspectedNode,this.owner.utils_makeOutline);}}}else{if(this.owner.viewInvisibles){if(is.ie){setTimeout("try{ktmls["+this.owner.counter+"].utils_makeTableCallback(ktmls["+this.owner.counter+"].inspectedNode, ktmls["+this.owner.counter+"].utils_unmakeOutline);}catch(e){}",50);}else{this.owner.utils_makeTableCallback(this.owner.inspectedNode,this.owner.utils_unmakeOutline);}}}
break;case"thead":var row_num=parseInt(propValue);if(TablePI_Update_THead(this.owner.inspectedNode,row_num)){if(!document.getElementById(this.ctrl_footer).value){util_safeSetFieldValue(this.ctrl_footer,'1');}}else{util_safeSetFieldValue(this.ctrl_header,'');util_safeSetFieldValue(this.ctrl_footer,'');};break;case"tfoot":var row_num=parseInt(propValue);if(TablePI_Update_TFoot(this.owner.inspectedNode,row_num)){if(!document.getElementById(this.ctrl_header).value){util_safeSetFieldValue(this.ctrl_header,'1');}}else{util_safeSetFieldValue(this.ctrl_header,'');util_safeSetFieldValue(this.ctrl_footer,'');};break;case"caption":var existing_caption=this.owner.inspectedNode.getElementsByTagName('caption')[0];if(existing_caption){existing_caption.innerHTML=propValue;}else{if(is.ie){existing_caption=this.owner.inspectedNode.createCaption();existing_caption.innerHTML=propValue;}else{var tmp=document.createElement('caption');tmp.innerHTML=propValue;this.owner.inspectedNode.insertBefore(tmp,this.owner.inspectedNode.firstChild);}
this.owner.logic_domSelect(this.owner.inspectedNode);}
break;case"captionalign":var existing_caption=this.owner.inspectedNode.getElementsByTagName('caption')[0];if(existing_caption){existing_caption.style.textAlign=propValue;}
break;case"captionposition":var existing_caption=this.owner.inspectedNode.getElementsByTagName('caption')[0];if(existing_caption){existing_caption.setAttribute('valign',propValue);}
break;default:this.owner.inspectedNode.setAttribute(propName,propValue);}}else{switch(propName){case"bgColor":this.owner.inspectedNode.style.backgroundColor="";try{document.getElementById(this.table_bgmonitor).style.backgroundColor="transparent";}catch(e){};break;case"bgimage":this.owner.inspectedNode.style.backgroundImage="";break;case"borderColor":this.owner.inspectedNode.style.borderColor="";this.owner.inspectedNode.style.borderWidth="";this.owner.inspectedNode.style.borderStyle="";try{document.getElementById(this.table_brdmonitor).style.backgroundColor="transparent";}catch(e){};var rows=this.owner.inspectedNode.rows;for(var j=0;j<rows.length;j++){for(var i=0;i<rows[j].cells.length;i++){rows[j].cells[i].removeAttribute("borderColor",propValue);rows[j].cells[i].style.borderStyle='';rows[j].cells[i].style.borderWidth='';rows[j].cells[i].style.borderColor='';}}
break;case"border":if(this.owner.viewInvisibles==true){if(propValue==''||propValue==0){if(is.ie){window.setTimeout('TablePI_lateBorders('+this.owner.counter+')',50);}else{this.owner.utils_makeTableCallback(inspected,this.owner.utils_makeOutline);}}else{this.owner.utils_makeTableCallback(inspected,this.owner.utils_unmakeOutline);}}
break;case"thead":var row_num=parseInt(propValue);if(TablePI_Update_THead(this.owner.inspectedNode,0)){util_safeSetFieldValue(this.ctrl_footer,'');}
break;case"tfoot":var row_num=parseInt(propValue);if(TablePI_Update_TFoot(this.owner.inspectedNode,0)){util_safeSetFieldValue(this.ctrl_header,'');};break;case"caption":var existing_caption=this.owner.inspectedNode.getElementsByTagName('caption')[0];if(existing_caption){this.owner.inspectedNode.deleteCaption();}
break;default:inspected.removeAttribute(propName);}}
try{fixFocusHack(0);}
catch(e){}};function TablePI_lateBorders(idx){try{ktmls[idx].utils_makeTableCallback(ktmls[idx].inspectedNode,ktmls[idx].utils_makeOutline);}catch(e){}};function TablePI_inspect(propName,propValue){var inspected=this.owner.inspectedNode;util_safeSetFieldValue(this.ctrl_id,inspected.getAttribute("id"));PropertiesUI_prop_getDimensions(this.owner.inspectedNode);util_safeSetFieldValue(this.ctrl_width,inspected.getAttribute("width"));util_safeSetFieldValue(this.ctrl_height,inspected.getAttribute("height"));util_safeSetFieldValue(this.ctrl_cellpadding,inspected.getAttribute("cellPadding"));util_safeSetFieldValue(this.ctrl_cellspacing,inspected.getAttribute("cellSpacing"));util_safeSetFieldValue(this.ctrl_border,inspected.getAttribute("border"));utility.dom.selectOption(document.getElementById(this.ctrl_align),inspected.getAttribute("align")||"");var _brdColor=inspected.style.borderColor;_brdColor=makeHexaColorCode(_brdColor);util_safeSetFieldValue(this.ctrl_brdcolor,_brdColor);try{document.getElementById(this.table_brdmonitor).style.backgroundColor=_brdColor;}catch(e){};var bgUrl=inspected.style.backgroundImage;if(bgUrl){var m=bgUrl.match(/url\(([^\)]*)\)/i);if(m){bgUrl=m[1];}
bgUrl=decodeURI(util_removeSiteNameFromHREF(this.owner,bgUrl.replace(/\?size=\d*$/,'')));}
util_safeSetFieldValue(this.ctrl_bgimage,bgUrl);var _bgColor=inspected.style.backgroundColor;_bgColor=makeHexaColorCode(_bgColor);util_safeSetFieldValue(this.ctrl_bgcolor,_bgColor);try{document.getElementById(this.ctrl_bgmonitor).style.backgroundColor=_bgColor;}catch(e){}
try{var _thead=inspected.getElementsByTagName('thead')[0];var _rows=_thead.getElementsByTagName('tr').length;util_safeSetFieldValue(this.ctrl_header,_rows);}catch(e){util_safeSetFieldValue(this.ctrl_header,'');util_safeSetFieldValue(this.ctrl_footer,'');};try{var _tfoot=inspected.getElementsByTagName('tfoot')[0];var _rows=_tfoot.getElementsByTagName('tr').length;util_safeSetFieldValue(this.ctrl_footer,_rows);}catch(e){util_safeSetFieldValue(this.ctrl_header,'');util_safeSetFieldValue(this.ctrl_footer,'');};var caption=(is.mozilla)?inspected.getElementsByTagName('caption')[0]:inspected.caption;util_safeSetFieldValue(this.ctrl_caption,caption?utility.string.getInnerText(caption.innerHTML):'');util_safeSetFieldValue(this.ctrl_summary,inspected.getAttribute('summary'));};function TablePI_Update_THead(tableObject,rowsNumber,calledByTFOOT){var tableRows=tableObject.rows.length;if(tableRows<3){return;};var THead=tableObject.getElementsByTagName('thead')[0];var thead_rows=THead?THead.getElementsByTagName('tr').length:0;var TBody=tableObject.getElementsByTagName('tbody')[0];var tbody_rows=TBody?TBody.getElementsByTagName('tr').length:1;var TFoot=tableObject.getElementsByTagName('tfoot')[0];var tfoot_rows=TFoot?TFoot.getElementsByTagName('tr').length:1;var avail_rows=tableRows-tfoot_rows-1;rowsNumber=(isNaN(rowsNumber))?0:rowsNumber;rowsNumber=Math.max(rowsNumber,0);rowsNumber=Math.min(rowsNumber,avail_rows);if((!THead)&&(rowsNumber!=0)){if(is.mozilla){var _thead=document.createElement('thead');var _ref=tableObject.getElementsByTagName('tr')[0];tableObject.insertBefore(_thead,tableObject.firstChild);}else{var _thead=tableObject.createTHead();};THead=_thead;};if(rowsNumber==0){for(var i=(thead_rows-1);i>=0;i--){var _current=THead.childNodes[i];var _ref=TBody.getElementsByTagName('tr')[0];if(_ref){TBody.insertBefore(_current,_ref);}else{TBody.appendChild(_current);}};while(THead){tableObject.removeChild(THead);THead=tableObject.getElementsByTagName('thead')[0];};if(TFoot){TablePI_Update_TFoot(tableObject,0,true);}}else if(rowsNumber<thead_rows){rowsNumber=thead_rows-rowsNumber;for(var j=(thead_rows-1);(j>((thead_rows-1)-rowsNumber));j--){var _current=THead.getElementsByTagName('tr')[j];var _ref=TBody.getElementsByTagName('tr')[0];if(_ref){TBody.insertBefore(_current,_ref);}else{TBody.appendChild(_current);}};if(!TFoot&&!calledByTFOOT){TablePI_Update_TFoot(tableObject,1,true);}}else if(rowsNumber>thead_rows){rowsNumber-=thead_rows;for(var l=0;l<rowsNumber;l++){var _current=TBody.getElementsByTagName('tr')[0];THead.appendChild(_current);};if(!TFoot&&!calledByTFOOT){TablePI_Update_TFoot(tableObject,1,true);}}
return true;};function TablePI_Update_TFoot(tableObject,rowsNumber,calledByTHEAD){var tableRows=tableObject.rows.length;if(tableRows<3){return false;};var THead=tableObject.getElementsByTagName('thead')[0];var thead_rows=THead?THead.getElementsByTagName('tr').length:1;var TBody=tableObject.getElementsByTagName('tbody')[0];var tbody_rows=TBody?TBody.getElementsByTagName('tr').length:1;var TFoot=tableObject.getElementsByTagName('tfoot')[0];var tfoot_rows=TFoot?TFoot.getElementsByTagName('tr').length:0;var avail_rows=tableRows-thead_rows-1;rowsNumber=(isNaN(rowsNumber))?0:rowsNumber;rowsNumber=Math.max(rowsNumber,0);rowsNumber=Math.min(rowsNumber,avail_rows);if(!TFoot&&(rowsNumber!=0)){if(is.mozilla){var _tfoot=document.createElement('tfoot');var _ref=THead?THead.nextSibling:tableObject.childNodes[0];tableObject.insertBefore(_tfoot,_ref);}else{var _tfoot=tableObject.createTFoot();};TFoot=_tfoot;};if((rowsNumber==0)&&TFoot){for(var i=0;i<tfoot_rows;i++){var _current=TFoot.getElementsByTagName('tr')[0];TBody.appendChild(_current);};while(TFoot){tableObject.removeChild(TFoot);TFoot=tableObject.getElementsByTagName('tfoot')[0];};if(THead&&!calledByTHEAD){TablePI_Update_THead(tableObject,0,true);}}else if(rowsNumber<tfoot_rows){rowsNumber=tfoot_rows-rowsNumber;for(var j=0;j<rowsNumber;j++){var _current=TFoot.getElementsByTagName('tr')[0];TBody.appendChild(_current);};if(!THead&&!calledByTHEAD){TablePI_Update_THead(tableObject,1,true);}}else if(rowsNumber>tfoot_rows){rowsNumber-=tfoot_rows;for(var l=0;l<rowsNumber;l++){var _current=Array_last(TBody.getElementsByTagName('tr'));var _ref=TFoot.getElementsByTagName('tr')[0];if(_ref){TFoot.insertBefore(_current,_ref);}else{TFoot.appendChild(_current);}};if(!THead&&!calledByTHEAD){TablePI_Update_THead(tableObject,1,true);}}
return true;};function makeHexaColorCode(inputValue){var colorInHexa=/\#[abcdef0123456789]{6}/i;if(colorInHexa.test(inputValue)){return inputValue.toUpperCase();}
var colorInRGB=/rgb\((\d{1,3})\,\s{0,1}(\d{1,3})\,\s{0,1}(\d{1,3})\)/i;if(colorInRGB.test(inputValue)){var _digits="0123456789ABCDEF";function decimal2hexa(val){var result=_digits.substr(val&15,1);while(val>15){val>>=4;result=_digits.substr(val&15,1)+result;}
return result;}
var values=inputValue.match(colorInRGB);var result='#';for(var i=1;i<=3;i++){var _current=values[i];var _translated=decimal2hexa(_current);_translated=(_translated.length==1)?'0'+_translated:_translated;result+=_translated;}
return result.toUpperCase();}
return'';};TablePI.prototype.apply=TablePI_apply;TablePI.prototype.inspect=TablePI_inspect;window.KtmlPIObjects["table"]=TablePI;